# Análise dos Boletins de Urna — Eleições 2026 (1º e 2º turnos)

Fonte: arquivos `bweb_*.csv` do TSE em `1o-turno/` e `2o-turno/` (um grupo por turno).

O notebook:
1. Converte os CSVs (≈35 GB no 1º turno) para um cache Parquet compacto usando **DuckDB** — feito só na primeira execução.
2. Mostra o **resultado das eleições** de cada turno (Presidente, Governador, Senador, Deputados).
3. Identifica **urnas com votos para um único candidato** em um cargo.
4. Mede a **variação de votos totais (comparecimento) por urna e por cidade** entre o 1º e o 2º turno e destaca as que variaram **mais de 10%**.

In [1]:
# Dependência: pip install duckdb pandas
import time
from pathlib import Path

import duckdb
import pandas as pd

BASE = Path.cwd()
GRUPOS = {1: BASE / '1o-turno', 2: BASE / '2o-turno'}
CACHE = BASE / 'cache'
SAIDA = BASE / 'resultados'
CACHE.mkdir(exist_ok=True)
SAIDA.mkdir(exist_ok=True)

LIMIAR_VARIACAO = 0.10          # 10%
CARGOS_CANDIDATO_UNICO = ['Presidente', 'Governador', 'Senador']  # inclua 'Deputado Federal'/'Deputado Estadual' se quiser
MIN_ELEITORES_CANDIDATO_UNICO = 0  # filtre urnas muito pequenas, se desejar

con = duckdb.connect()
con.execute("SET memory_limit='12GB'")
con.execute(f"SET temp_directory='{CACHE / 'tmp'}'")

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 200)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

## 1. Cache Parquet

Para cada turno são gerados dois arquivos:
- `votos_tN.parquet` — votos por urna/cargo/votável;
- `secoes_tN.parquet` — uma linha por urna (seção) com aptos, comparecimento e abstenções.

Apague a pasta `cache/` para reprocessar os CSVs.

In [2]:
def gerar_cache(turno: int, pasta: Path):
    votos_pq = CACHE / f'votos_t{turno}.parquet'
    secoes_pq = CACHE / f'secoes_t{turno}.parquet'
    if votos_pq.exists() and secoes_pq.exists():
        print(f'Turno {turno}: cache já existe')
        return
    t0 = time.time()
    csvs = str(pasta / 'bweb_*.csv')
    con.execute(f'''
        CREATE OR REPLACE TEMP VIEW bruto AS
        SELECT
            SG_UF                                   AS uf,
            TRY_CAST(CD_MUNICIPIO AS INTEGER)       AS cd_municipio,
            NM_MUNICIPIO                            AS municipio,
            TRY_CAST(NR_ZONA AS INTEGER)            AS zona,
            TRY_CAST(NR_SECAO AS INTEGER)           AS secao,
            TRY_CAST(NR_LOCAL_VOTACAO AS INTEGER)   AS local_votacao,
            TRY_CAST(CD_CARGO_PERGUNTA AS INTEGER)  AS cd_cargo,
            DS_CARGO_PERGUNTA                       AS cargo,
            DS_TIPO_VOTAVEL                         AS tipo_votavel,
            TRY_CAST(NR_VOTAVEL AS INTEGER)         AS nr_votavel,
            NM_VOTAVEL                              AS candidato,
            SG_PARTIDO                              AS partido,
            TRY_CAST(QT_VOTOS AS INTEGER)           AS votos,
            TRY_CAST(QT_APTOS AS INTEGER)           AS aptos,
            TRY_CAST(QT_COMPARECIMENTO AS INTEGER)  AS comparecimento,
            TRY_CAST(QT_ABSTENCOES AS INTEGER)      AS abstencoes,
            DS_TIPO_URNA                            AS tipo_urna,
            NR_URNA_EFETIVADA                       AS nr_urna
        FROM read_csv('{csvs}', delim=';', quote='"', header=true,
                      encoding='latin-1', all_varchar=true, parallel=true)
        WHERE TRY_CAST(CD_CARGO_PERGUNTA AS INTEGER) > 0
    ''')
    # Uma única leitura dos CSVs; as colunas por seção repetem-se mas comprimem bem
    con.execute(f"COPY (SELECT * FROM bruto) TO '{votos_pq}' (FORMAT parquet, COMPRESSION zstd)")
    print(f'Turno {turno}: votos gravados em {time.time() - t0:,.0f}s')
    con.execute(f'''
        COPY (
            SELECT uf, cd_municipio, any_value(municipio) AS municipio, zona, secao,
                   any_value(local_votacao) AS local_votacao,
                   max(aptos) AS aptos, max(comparecimento) AS comparecimento,
                   max(abstencoes) AS abstencoes,
                   any_value(tipo_urna) AS tipo_urna, any_value(nr_urna) AS nr_urna
            FROM read_parquet('{votos_pq}')
            GROUP BY uf, cd_municipio, zona, secao
        ) TO '{secoes_pq}' (FORMAT parquet, COMPRESSION zstd)
    ''')
    print(f'Turno {turno}: seções gravadas em {time.time() - t0:,.0f}s')


for turno, pasta in GRUPOS.items():
    gerar_cache(turno, pasta)

for turno in GRUPOS:
    con.execute(f"CREATE OR REPLACE VIEW votos_t{turno} AS SELECT * FROM read_parquet('{CACHE}/votos_t{turno}.parquet')")
    con.execute(f"CREATE OR REPLACE VIEW secoes_t{turno} AS SELECT * FROM read_parquet('{CACHE}/secoes_t{turno}.parquet')")

q = lambda sql: con.sql(sql).df()

Turno 1: cache já existe
Turno 2: cache já existe

## 2. Visão geral por turno

In [3]:
visao = pd.concat([
    q(f'''
        SELECT {t} AS turno, count(*) AS urnas, count(DISTINCT uf || cd_municipio) AS municipios,
               sum(aptos) AS aptos, sum(comparecimento) AS comparecimento,
               sum(abstencoes) AS abstencoes,
               round(100.0 * sum(comparecimento) / sum(aptos), 2) AS pct_comparecimento
        FROM secoes_t{t}
    ''') for t in GRUPOS
])
visao

   turno   urnas  municipios          aptos  comparecimento    abstencoes  pct_comparecimento
0      1  499206        5716 158,745,007.00  125,275,835.00 33,469,172.00               78.92
0      2  499205        5715 158,744,977.00  128,236,074.00 30,508,903.00               80.78

## 3. Resultado das eleições

`resultado(turno, cargo)` soma os votos por candidato. Percentuais calculados sobre **votos válidos** (nominais + legenda).
Para Presidente o resultado é nacional (inclui exterior, UF `ZZ`); para os demais cargos é por UF.

In [4]:
def resultado(turno: int, cargo: str, por_uf: bool = True) -> pd.DataFrame:
    uf_col = 'uf, ' if por_uf else ''
    part = 'PARTITION BY uf' if por_uf else ''
    return q(f'''
        WITH t AS (
            SELECT {uf_col} nr_votavel, candidato, partido, sum(votos) AS votos
            FROM votos_t{turno}
            WHERE cargo = '{cargo}' AND tipo_votavel IN ('Nominal', 'Legenda')
            GROUP BY ALL
        )
        SELECT {uf_col} nr_votavel, candidato, partido, votos,
               round(100.0 * votos / sum(votos) OVER ({part}), 2) AS pct_validos,
               rank() OVER ({part} ORDER BY votos DESC) AS posicao
        FROM t
        ORDER BY {uf_col} votos DESC
    ''')


def resumo_brancos_nulos(turno: int, cargo: str) -> pd.DataFrame:
    return q(f'''
        SELECT tipo_votavel, sum(votos) AS votos,
               round(100.0 * sum(votos) / sum(sum(votos)) OVER (), 2) AS pct_total
        FROM votos_t{turno} WHERE cargo = '{cargo}'
        GROUP BY tipo_votavel ORDER BY votos DESC
    ''')


def vencedores_por_uf(turno: int, cargo: str, vagas: int = 1) -> pd.DataFrame:
    df = resultado(turno, cargo)
    return df[df.posicao <= max(vagas, 2)].reset_index(drop=True)

### 3.1 — 1º turno

In [5]:
print('PRESIDENTE — 1º turno (nacional)')
display(resultado(1, 'Presidente', por_uf=False))
display(resumo_brancos_nulos(1, 'Presidente'))

PRESIDENTE — 1º turno (nacional)

    nr_votavel                  candidato    partido         votos  pct_validos  posicao
0           22           FLAVIO BOLSONARO         PL 56,104,503.00        47.03        1
1           13                       LULA         PT 53,879,538.00        45.16        2
2           70      ESCRITOR AUGUSTO CURY     AVANTE  3,448,569.00         2.89        3
3           14               RENAN SANTOS     MISSÃO  2,675,887.00         2.24        4
4           55             RONALDO CAIADO        PSD  2,605,148.00         2.18        5
5           30                       ZEMA       NOVO    326,488.00         0.27        6
6           80                     SAMARA         UP    122,911.00         0.10        7
7           16                 HERTZ DIAS       PSTU     43,103.00         0.04        8
8           27             CLARIANA BARAO         DC     40,043.00         0.03        9
9           21             EDMILSON COSTA        PCB     22,693.00         0.02       10
10          35  VETERINÁRIO WILSON GRASSI  DEMOCRATA     16,881.00         0.01       11
11          29          RUI COSTA PIMENTA        PCO     15,024.00         0.01       12
12          28         LEONARDO AVALANCHE       PRTB      5,246.00         0.00       13

  tipo_votavel          votos  pct_total
0      Nominal 119,306,034.00      95.23
1         Nulo   3,669,003.00       2.93
2       Branco   2,300,798.00       1.84

In [6]:
print('PRESIDENTE — 1º turno por UF (votos por candidato)')
pres1_uf = resultado(1, 'Presidente').pivot_table(index='uf', columns='candidato', values='pct_validos')
pres1_uf

PRESIDENTE — 1º turno por UF (votos por candidato)

candidato,CLARIANA BARAO,EDMILSON COSTA,ESCRITOR AUGUSTO CURY,FLAVIO BOLSONARO,HERTZ DIAS,LEONARDO AVALANCHE,LULA,RENAN SANTOS,RONALDO CAIADO,RUI COSTA PIMENTA,SAMARA,VETERINÁRIO WILSON GRASSI,ZEMA
uf,,,,,,,,,,,,,
AC,0.05,0.03,2.88,64.55,0.02,0.00,28.73,1.70,1.83,0.01,0.07,0.01,0.12
AL,0.03,0.01,2.33,40.45,0.02,0.00,54.73,1.48,0.78,0.01,0.07,0.01,0.06
AM,0.04,0.01,3.57,44.99,0.02,0.00,48.23,1.63,1.30,0.01,0.09,0.01,0.08
AP,0.05,0.01,4.10,45.66,0.03,0.00,45.71,2.44,1.79,0.01,0.11,0.01,0.07
BA,0.02,0.02,2.28,28.53,0.02,0.00,66.17,1.37,1.43,0.01,0.05,0.01,0.08
CE,0.02,0.01,2.50,31.27,0.03,0.00,63.28,1.92,0.81,0.01,0.06,0.01,0.08
DF,0.04,0.02,2.59,51.31,0.05,0.00,38.11,2.63,4.80,0.02,0.13,0.02,0.28
ES,0.04,0.02,2.89,54.78,0.03,0.01,37.76,2.36,1.74,0.01,0.09,0.01,0.26
GO,0.01,0.01,1.41,53.60,0.02,0.00,31.06,1.41,12.33,0.01,0.05,0.01,0.07
MA,0.02,0.01,2.12,30.89,0.04,0.01,63.99,1.51,1.25,0.01,0.04,0.01,0.11
MG,0.03,0.02,3.42,48.24,0.03,0.00,43.32,2.06,1.92,0.01,0.09,0.01,0.82
MS,0.04,0.02,2.63,58.60,0.02,0.01,34.68,2.14,1.56,0.01,0.09,0.01,0.19
MT,0.09,0.01,2.01,65.14,0.02,0.00,29.18,1.66,1.66,0.01,0.08,0.01,0.12
PA,0.03,0.01,2.57,44.50,0.02,0.00,49.91,1.73,1.07,0.01,0.08,0.01,0.06
PB,0.02,0.01,2.94,33.07,0.02,0.00,61.31,1.68,0.78,0.01,0.06,0.01,0.08
PE,0.02,0.01,2.46,31.03,0.02,0.00,63.45,1.53,1.31,0.01,0.04,0.01,0.11
PI,0.02,0.01,2.22,24.09,0.02,0.00,70.99,1.50,1.01,0.01,0.05,0.01,0.06
PR,0.04,0.02,3.11,59.91,0.03,0.00,31.20,2.69,2.60,0.01,0.10,0.01,0.26
RJ,0.04,0.03,2.64,53.01,0.04,0.00,39.41,2.26,2.13,0.02,0.15,0.02,0.23
RN,0.02,0.02,2.77,34.77,0.03,0.00,59.75,1.70,0.79,0.01,0.06,0.01,0.07
RO,0.04,0.02,2.61,67.45,0.02,0.01,25.89,1.98,1.75,0.01,0.09,0.01,0.14
RR,0.05,0.01,2.64,71.05,0.02,0.00,22.86,2.03,1.12,0.01,0.09,0.01,0.10
RS,0.03,0.02,3.04,55.64,0.03,0.00,35.73,2.61,2.47,0.02,0.10,0.01,0.30
SC,0.03,0.02,2.98,66.65,0.03,0.00,25.04,2.95,1.78,0.01,0.11,0.01,0.37
SE,0.03,0.01,2.85,30.63,0.02,0.00,62.75,1.57,1.95,0.01,0.07,0.01,0.08
SP,0.04,0.02,3.59,51.93,0.06,0.01,38.20,3.23,2.33,0.02,0.17,0.02,0.38
TO,0.02,0.01,2.41,50.44,0.01,0.00,43.42,1.40,2.17,0.01,0.04,0.01,0.06
ZZ,0.25,0.13,2.94,43.47,0.11,0.04,47.55,2.59,1.42,0.06,0.32,0.11,1.01

In [7]:
print('GOVERNADOR — 1º turno: dois primeiros colocados por UF')
vencedores_por_uf(1, 'Governador')

GOVERNADOR — 1º turno: dois primeiros colocados por UF

    uf  nr_votavel                  candidato       partido         votos  pct_validos  posicao
0   AC          11               MAILZA ASSIS            PP    218,760.00        49.76        1
1   AC          10                  ALAN RICK  REPUBLICANOS    141,859.00        32.27        2
2   AL          45                        JHC          PSDB    892,484.00        52.20        1
3   AL          15                RENAN FILHO           MDB    809,796.00        47.37        2
4   AM          55                  OMAR AZIZ           PSD    841,846.00        40.63        1
5   AM          22  PROFESSORA MARIA DO CARMO            PL    507,335.00        24.49        2
6   AP          55                 DR. FURLAN           PSD    281,595.00        62.75        1
7   AP          44                     CLÉCIO         UNIÃO    165,900.00        36.97        2
8   BA          13         JERÔNIMO RODRIGUES            PT  4,626,509.00        55.80        1
9   BA          44                   ACM NETO         UNIÃO  3,625,227.00        43.72        2
10  CE          13          ELMANO DE FREITAS            PT  2,875,573.00        53.19        1
11  CE          45                 CIRO GOMES          PSDB  2,498,891.00        46.22        2
12  DF          11                CELINA LEÃO            PP    825,530.00        49.68        1
13  DF          13              LEANDRO GRASS            PT    569,930.00        34.30        2
14  ES          10           LORENZO PAZOLINI  REPUBLICANOS  1,048,633.00        49.65        1
15  ES          15            RICARDO FERRAÇO           MDB    719,397.00        34.06        2
16  GO          15              DANIEL VILELA           MDB  2,148,218.00        59.17        1
17  GO          22              WILDER MORAIS            PL    797,141.00        21.96        2
18  MA          55             EDUARDO BRAIDE           PSD  2,104,122.00        54.02        1
19  MA          15            ORLEANS BRANDÃO           MDB  1,354,044.00        34.76        2
20  MG          10          CLEITINHO AZEVEDO  REPUBLICANOS  6,321,590.00        55.40        1
21  MG          13             PATRUS ANANIAS            PT  3,006,088.00        26.34        2
22  MS          11             EDUARDO RIEDEL            PP    914,323.00        67.07        1
23  MS          13                 FÁBIO TRAD            PT    322,807.00        23.68        2
24  MT          10           OTAVIANO PIVETTA  REPUBLICANOS  1,128,099.00        60.77        1
25  MT          22        WELLINGTON FAGUNDES            PL    430,442.00        23.19        2
26  PA          20                 DR. DANIEL          PODE  2,345,721.00        51.36        1
27  PA          15               HANA GHASSAN           MDB  2,125,084.00        46.53        2
28  PB          11              LUCAS RIBEIRO            PP  1,470,252.00        64.28        1
29  PB          22               EFRAIM FILHO            PL    552,836.00        24.17        2
30  PE          55                RAQUEL LYRA           PSD  2,805,438.00        53.27        1
31  PE          40                JOÃO CAMPOS           PSB  2,360,469.00        44.82        2
32  PI          13            RAFAEL FONTELES            PT  1,436,697.00        70.90        1
33  PI          11             JOEL RODRIGUES            PP    557,972.00        27.54        2
34  PR          22                SERGIO MORO            PL  3,127,911.00        50.10        1
35  PR          55                SANDRO ALEX           PSD  1,583,764.00        25.37        2
36  RJ          22               DOUGLAS RUAS            PL  4,271,199.00        49.27        1
37  RJ          55               EDUARDO PAES           PSD  3,706,984.00        42.76        2
38  RN          44                    ALLYSON         UNIÃO    733,809.00        36.90        1
39  RN          13               CADU DE LULA            PT    718,300.00        36.12        2
40  RO          22             MARCOS ROGÉRIO            PL    537,370.00        56.86        1
41  RO          55             ADAILTON FURIA           PSD    189,547.00        20.06        2
42  RR          22            ARTHUR HENRIQUE            PL    220,809.00        69.13        1
43  RR          10            SOLDADO SAMPAIO  REPUBLICANOS     93,434.00        29.25        2
44  RS          22                      ZUCCO            PL  3,516,048.00        58.05        1
45  RS          12            JULIANA BRIZOLA           PDT  1,917,374.00        31.65        2
46  SC          22             JORGINHO MELLO            PL  2,942,386.00        68.98        1
47  SC          40             GELSON MERÍSIO           PSB    668,021.00        15.66        2
48  SE          55                      FÁBIO           PSD    727,291.00        57.71        1
49  SE          10    VALMIR DE FRANCISQUINHO  REPUBLICANOS    459,908.00        36.49        2
50  SP          10                   TARCÍSIO  REPUBLICANOS 14,491,874.00        62.59        1
51  SP          13            FERNANDO HADDAD            PT  8,423,656.00        36.38        2
52  TO          44         PROFESSORA DORINHA         UNIÃO    386,260.00        45.46        1
53  TO          45          VICENTINHO JÚNIOR          PSDB    372,848.00        43.88        2

In [8]:
print('SENADOR — 1º turno: três primeiros colocados por UF')
sen = resultado(1, 'Senador')
sen[sen.posicao <= 3].reset_index(drop=True)

SENADOR — 1º turno: três primeiros colocados por UF

    uf  nr_votavel                    candidato       partido         votos  pct_validos  posicao
0   AC         222                MARCIO BITTAR            PL    223,972.00        25.59        1
1   AC         100                   MARA ROCHA  REPUBLICANOS    157,104.00        17.95        2
2   AC         111               GLADSON CAMELÍ            PP    145,244.00        16.59        3
3   AL         111                  ARTHUR LIRA            PP    948,703.00        28.87        1
4   AL         456                   MARINA JHC          PSDB    926,860.00        28.20        2
5   AL         151                        RENAN           MDB    731,045.00        22.24        3
6   AM         155                EDUARDO BRAGA           MDB  1,240,471.00        31.81        1
7   AM         455               PLINIO VALÉRIO          PSDB    948,793.00        24.33        2
8   AM         222         CAPITÃO ALBERTO NETO            PL    909,155.00        23.32        3
9   AP         200                RAYSSA FURLAN          PODE    264,799.00        29.98        1
10  AP         555                LUCAS BARRETO           PSD    213,948.00        24.22        2
11  AP         130                     RANDOLFE            PT    163,857.00        18.55        3
12  BA         133                    RUI COSTA            PT  4,335,196.00        30.07        1
13  BA         130                JAQUES WAGNER            PT  3,986,690.00        27.65        2
14  BA         100               ANGELO CORONEL  REPUBLICANOS  2,898,885.00        20.11        3
15  CE         400                    CID GOMES           PSB  3,033,562.00        31.22        1
16  CE         180                    LUIZIANNE          REDE  2,822,806.00        29.05        2
17  CE         445               CAPITÃO WAGNER         UNIÃO  2,011,388.00        20.70        3
18  DF         222           MICHELLE BOLSONARO            PL    938,496.00        28.99        1
19  DF         223                    BIA KICIS            PL    886,616.00        27.39        2
20  DF         123               LEILA DO VÔLEI           PDT    686,340.00        21.20        3
21  ES         400            RENATO CASAGRANDE           PSB    995,361.00        24.70        1
22  ES         100                EVAIR DE MELO  REPUBLICANOS    982,978.00        24.39        2
23  ES         222               MAGUINHA MALTA            PL    761,722.00        18.90        3
24  GO         222                GUSTAVO GAYER            PL  1,639,247.00        24.53        1
25  GO         444              GRACINHA CAIADO         UNIÃO  1,458,522.00        21.83        2
26  GO         155          DR. ZACHARIAS CALIL           MDB    998,319.00        14.94        3
27  MA         111                       FUFUCA            PP  1,530,187.00        21.43        1
28  MA         300               LAHESIO BONFIM          NOVO  1,471,859.00        20.61        2
29  MA         151               ROSEANA SARNEY           MDB  1,171,634.00        16.41        3
30  MG         222               DOMINGOS SÁVIO            PL  4,968,829.00        24.21        1
31  MG         131               MARÍLIA CAMPOS            PT  3,990,864.00        19.44        2
32  MG         555                 CARLOS VIANA           PSD  3,583,487.00        17.46        3
33  MS         222            REINALDO AZAMBUJA            PL    903,554.00        34.61        1
34  MS         221               CAPITÃO CONTAR            PL    856,045.00        32.79        2
35  MS         133                VANDER LOUBET            PT    361,920.00        13.86        3
36  MT         444                 MAURO MENDES         UNIÃO  1,187,352.00        33.21        1
37  MT         222                  ZÉ MEDEIROS            PL    977,777.00        27.35        2
38  MT         150                 JANAINA RIVA           MDB    519,434.00        14.53        3
39  PA         151                       HELDER           MDB  2,342,070.00        26.10        1
40  PA         444                       CHICÃO         UNIÃO  2,014,409.00        22.45        2
41  PA         222          DELEGADO ÉDER MAURO            PL  1,997,768.00        22.26        3
42  PB         400                 JOAO AZEVÊDO           PSB  1,391,994.00        32.50        1
43  PB         155                    VENEZIANO           MDB    974,550.00        22.76        2
44  PB         100                        NABOR  REPUBLICANOS    895,398.00        20.91        3
45  PE         130               HUMBERTO COSTA            PT  2,531,389.00        27.19        1
46  PE         123               MARÍLIA ARRAES           PDT  2,325,127.00        24.97        2
47  PE         222               MENDONÇA FILHO            PL  1,728,587.00        18.57        3
48  PI         151               MARCELO CASTRO           MDB  1,307,833.00        35.61        1
49  PI         555  JÚLIO CÉSAR O JULIM DO LULA           PSD    989,146.00        26.93        2
50  PI         111                CIRO NOGUEIRA            PP    904,961.00        24.64        3
51  PR         222                FILIPE BARROS            PL  3,148,583.00        27.25        1
52  PR         300             DELTAN DALLAGNOL          NOVO  2,904,594.00        25.14        2
53  PR         100               ALEXANDRE CURI  REPUBLICANOS  1,947,135.00        16.85        3
54  RJ         222              CARLOS PORTINHO            PL  4,264,932.00        26.77        1
55  RJ         221                 CARLOS JORDY            PL  3,912,405.00        24.56        2
56  RJ         131            BENEDITA DA SILVA            PT  3,220,765.00        20.22        3
57  RN         200           STYVENSON VALENTIM          PODE  1,055,000.00        29.25        1
58  RN         131              SAMANDA DE LULA            PT    635,924.00        17.63        2
59  RN         555                 ZENAIDE MAIA           PSD    630,159.00        17.47        3
60  RO         221          DR. FERNANDO MÁXIMO            PL    570,799.00        31.97        1
61  RO         222                 BRUNO SCHEID            PL    474,226.00        26.56        2
62  RO         111              SÍLVIA CRISTINA            PP    304,061.00        17.03        3
63  RR         227                    NICOLETTI            PL    138,269.00        22.68        1
64  RR         155                TERESA SURITA           MDB    117,270.00        19.24        2
65  RR         555             HELENA DA ASATUR           PSD    106,652.00        17.50        3
66  RS         222                    SANDERSON            PL  3,453,316.00        30.11        1
67  RS         300            MARCEL VAN HATTEM          NOVO  3,449,053.00        30.08        2
68  RS         500              MANUELA D'ÁVILA          PSOL  1,957,697.00        17.07        3
69  SC         221                CAROL DE TONI            PL  2,694,918.00        33.46        1
70  SC         222             CARLOS BOLSONARO            PL  2,041,840.00        25.35        2
71  SC         111              ESPERIDIÃO AMIN            PP  1,233,034.00        15.31        3
72  SE         131             ROGERIO CARVALHO            PT    511,142.00        21.91        1
73  SE         155          DELEGADO ALESSANDRO           MDB    399,775.00        17.13        2
74  SE         101         DELEGADO ANDRÉ DAVID  REPUBLICANOS    378,710.00        16.23        3
75  SP         111            GUILHERME DERRITE            PP 13,273,880.00        30.50        1
76  SP         222               ANDRÉ DO PRADO            PL 12,703,089.00        29.19        2
77  SP         400                 SIMONE TEBET           PSB  8,342,968.00        19.17        3
78  TO         222                EDUARDO GOMES            PL    450,191.00        27.22        1
79  TO         153          ALEXANDRE GUIMARÃES           MDB    316,786.00        19.16        2
80  TO         100                   ELI BORGES  REPUBLICANOS    271,829.00        16.44        3

In [9]:
for cargo in ['Deputado Federal', 'Deputado Estadual']:
    print(f'{cargo.upper()} — 1º turno: votos válidos (nominal + legenda) por partido, nacional')
    display(q(f'''
        SELECT partido, sum(votos) AS votos,
               round(100.0 * sum(votos) / sum(sum(votos)) OVER (), 2) AS pct_validos
        FROM votos_t1
        WHERE cargo = '{cargo}' AND tipo_votavel IN ('Nominal', 'Legenda')
        GROUP BY partido ORDER BY votos DESC
    '''))

DEPUTADO FEDERAL — 1º turno: votos válidos (nominal + legenda) por partido, nacional

          partido         votos  pct_validos
0              PL 25,830,609.00        22.64
1              PT 14,798,202.00        12.97
2             PSD  9,403,436.00         8.24
3    REPUBLICANOS  7,987,717.00         7.00
4             MDB  7,924,588.00         6.94
5           UNIÃO  7,877,391.00         6.90
6              PP  7,620,142.00         6.68
7            PODE  5,900,293.00         5.17
8            PSOL  5,312,186.00         4.66
9             PSB  5,013,154.00         4.39
10           PSDB  2,915,967.00         2.56
11           NOVO  2,914,890.00         2.55
12            PDT  1,880,161.00         1.65
13         AVANTE  1,844,272.00         1.62
14             PV  1,368,491.00         1.20
15          PCDOB  1,306,368.00         1.14
16         MISSÃO  1,224,340.00         1.07
17            PRD  1,205,438.00         1.06
18  SOLIDARIEDADE    933,008.00         0.82
19      CIDADANIA    291,377.00         0.26
20           REDE    264,222.00         0.23
21             DC    122,753.00         0.11
22       MOBILIZA     46,373.00         0.04
23             UP     45,431.00         0.04
24      DEMOCRATA     34,119.00         0.03
25           PSTU     18,696.00         0.02
26           AGIR     17,171.00         0.02
27            PCO      7,687.00         0.01

DEPUTADO ESTADUAL — 1º turno: votos válidos (nominal + legenda) por partido, nacional

          partido         votos  pct_validos
0              PL 22,522,692.00        20.17
1              PT 15,454,635.00        13.84
2             PSD 11,410,805.00        10.22
3             MDB 10,203,697.00         9.14
4    REPUBLICANOS  7,116,567.00         6.37
5              PP  6,847,675.00         6.13
6           UNIÃO  6,309,668.00         5.65
7            PODE  4,756,298.00         4.26
8             PSB  4,548,694.00         4.07
9            PSOL  4,150,226.00         3.72
10           PSDB  3,177,392.00         2.85
11            PDT  2,651,303.00         2.37
12         AVANTE  2,215,914.00         1.98
13           NOVO  2,208,032.00         1.98
14             PV  1,698,292.00         1.52
15            PRD  1,303,839.00         1.17
16          PCDOB  1,123,169.00         1.01
17         MISSÃO    793,533.00         0.71
18           AGIR    735,210.00         0.66
19  SOLIDARIEDADE    663,262.00         0.59
20       MOBILIZA    490,057.00         0.44
21           REDE    483,081.00         0.43
22      DEMOCRATA    274,240.00         0.25
23      CIDADANIA    244,516.00         0.22
24             DC    198,340.00         0.18
25             UP     46,471.00         0.04
26           PSTU     22,661.00         0.02
27            PCB      6,241.00         0.01
28            PCO      6,000.00         0.01

In [10]:
print('DEPUTADO FEDERAL — 10 mais votados por UF')
dep = resultado(1, 'Deputado Federal')
dep[(dep.posicao <= 10) & (dep.candidato != dep.partido)].reset_index(drop=True)

DEPUTADO FEDERAL — 10 mais votados por UF

     uf  nr_votavel         candidato       partido     votos  pct_validos  posicao
0    AC        1101      SOCORRO NERI            PP 39,587.00         8.45        1
1    AC        4444   DR. FÁBIO RUEDA         UNIÃO 33,203.00         7.08        2
2    AC        4422   CORONEL ULYSSES         UNIÃO 33,155.00         7.07        3
3    AC        1533       PEDRO LONGO           MDB 26,263.00         5.60        4
4    AC        1010    ROBERTO DUARTE  REPUBLICANOS 24,854.00         5.30        5
..   ..         ...               ...           ...       ...          ...      ...
265  TO        2222    FILIPE MARTINS            PL 64,068.00         7.06        6
266  TO        2022  SANDOVAL CARDOSO          PODE 61,747.00         6.81        7
267  TO        1011    ALFREDO JÚNIOR  REPUBLICANOS 48,253.00         5.32        8
268  TO        4422   CORONEL BARBOSA         UNIÃO 28,544.00         3.15        9
269  TO        2088       TIAGO DIMAS          PODE 27,910.00         3.08       10

[270 rows x 7 columns]

### 3.2 — 2º turno

In [11]:
print('PRESIDENTE — 2º turno (nacional)')
display(resultado(2, 'Presidente', por_uf=False))
display(resumo_brancos_nulos(2, 'Presidente'))

PRESIDENTE — 2º turno (nacional)

   nr_votavel         candidato partido         votos  pct_validos  posicao
0          13              LULA      PT 64,256,232.00        51.79        1
1          22  FLAVIO BOLSONARO      PL 59,826,041.00        48.21        2

  tipo_votavel          votos  pct_total
0      Nominal 124,082,273.00      96.76
1         Nulo   2,723,305.00       2.12
2       Branco   1,430,496.00       1.12

In [12]:
print('PRESIDENTE — 2º turno por UF (% válidos)')
resultado(2, 'Presidente').pivot_table(index='uf', columns='candidato', values='pct_validos')

PRESIDENTE — 2º turno por UF (% válidos)

candidato  FLAVIO BOLSONARO  LULA
uf
AC                    66.57 33.43
AL                    39.23 60.77
AM                    45.98 54.02
AP                    47.12 52.88
BA                    28.69 71.31
CE                    31.07 68.93
DF                    54.28 45.72
ES                    56.37 43.63
GO                    59.66 40.34
MA                    30.46 69.54
MG                    49.57 50.43
MS                    59.60 40.40
MT                    66.06 33.94
PA                    44.98 55.02
PB                    32.54 67.46
PE                    30.80 69.20
PI                    24.12 75.88
PR                    62.58 37.42
RJ                    53.10 46.90
RN                    34.28 65.72
RO                    69.61 30.39
RR                    72.46 27.54
RS                    57.84 42.16
SC                    69.42 30.58
SE                    30.47 69.53
SP                    53.85 46.15
TO                    51.37 48.63
ZZ                    46.14 53.86

In [13]:
print('GOVERNADOR — 2º turno por UF')
resultado(2, 'Governador')

GOVERNADOR — 2º turno por UF

    uf  nr_votavel                  candidato       partido        votos  pct_validos  posicao
0   AC          11               MAILZA ASSIS            PP   272,635.00        66.21        1
1   AC          10                  ALAN RICK  REPUBLICANOS   139,108.00        33.79        2
2   AM          55                  OMAR AZIZ           PSD 1,273,975.00        61.42        1
3   AM          22  PROFESSORA MARIA DO CARMO            PL   800,328.00        38.58        2
4   DF          11                CELINA LEÃO            PP   987,142.00        57.18        1
5   DF          13              LEANDRO GRASS            PT   739,130.00        42.82        2
6   ES          10           LORENZO PAZOLINI  REPUBLICANOS 1,151,818.00        52.17        1
7   ES          15            RICARDO FERRAÇO           MDB 1,056,119.00        47.83        2
8   RN          13               CADU DE LULA            PT 1,073,024.00        50.77        1
9   RN          44                    ALLYSON         UNIÃO 1,040,399.00        49.23        2
10  TO          45          VICENTINHO JÚNIOR          PSDB   562,083.00        64.52        1
11  TO          44         PROFESSORA DORINHA         UNIÃO   309,076.00        35.48        2

## 4. Urnas com votos para um único candidato

Para cada urna e cargo, contamos quantos candidatos (votos **nominais**) receberam ao menos 1 voto.
Se apenas **um** candidato recebeu votos, a urna é marcada. Brancos e nulos são mostrados à parte.
Ajuste `CARGOS_CANDIDATO_UNICO` e `MIN_ELEITORES_CANDIDATO_UNICO` na célula de configuração.

In [14]:
cargos_sql = ', '.join(f"'{c}'" for c in CARGOS_CANDIDATO_UNICO)


def candidato_unico(turno: int) -> pd.DataFrame:
    return q(f'''
        WITH por_urna AS (
            SELECT uf, cd_municipio, zona, secao, cargo,
                   count(*) FILTER (WHERE tipo_votavel = 'Nominal' AND votos > 0) AS candidatos_com_voto,
                   sum(votos) FILTER (WHERE tipo_votavel = 'Nominal')  AS votos_nominais,
                   coalesce(sum(votos) FILTER (WHERE tipo_votavel = 'Branco'), 0) AS brancos,
                   coalesce(sum(votos) FILTER (WHERE tipo_votavel = 'Nulo'), 0)   AS nulos,
                   arg_max(candidato, votos) FILTER (WHERE tipo_votavel = 'Nominal') AS candidato,
                   arg_max(partido, votos)   FILTER (WHERE tipo_votavel = 'Nominal') AS partido
            FROM votos_t{turno}
            WHERE cargo IN ({cargos_sql})
            GROUP BY ALL
        )
        SELECT {turno} AS turno, p.uf, s.municipio, p.zona, p.secao, s.local_votacao, p.cargo,
               p.candidato, p.partido, p.votos_nominais, p.brancos, p.nulos,
               s.aptos, s.comparecimento, s.nr_urna
        FROM por_urna p
        JOIN secoes_t{turno} s USING (uf, cd_municipio, zona, secao)
        WHERE p.candidatos_com_voto = 1
          AND s.comparecimento >= {MIN_ELEITORES_CANDIDATO_UNICO}
        ORDER BY p.cargo, s.comparecimento DESC
    ''')


unico = pd.concat([candidato_unico(t) for t in GRUPOS], ignore_index=True)
print(f'{len(unico):,} ocorrências (urna × cargo) com votos para um único candidato')
unico.groupby(['turno', 'cargo']).agg(urnas=('secao', 'size'),
                                      votos_nominais=('votos_nominais', 'sum'),
                                      maior_urna=('comparecimento', 'max'))

204 ocorrências (urna × cargo) com votos para um único candidato

                  urnas  votos_nominais  maior_urna
turno cargo
1     Governador     21        1,613.00         297
      Presidente     40        3,764.00         283
      Senador         1          108.00         238
2     Governador     32        5,912.00         365
      Presidente    110       15,156.00         365

In [15]:
print('Distribuição por UF / município')
(unico.groupby(['turno', 'cargo', 'uf', 'municipio'])
      .agg(urnas=('secao', 'size'), votos=('votos_nominais', 'sum'),
           candidatos=('candidato', lambda s: ', '.join(sorted(s.dropna().unique()))))
      .sort_values('urnas', ascending=False))

Distribuição por UF / município

                                               urnas    votos                candidatos
turno cargo      uf municipio
2     Presidente RR UIRAMUTÃ                       7 1,163.00                      LULA
                 AM ATALAIA DO NORTE               5 1,027.00                      LULA
                    SÃO GABRIEL DA CACHOEIRA       5   954.00                      LULA
      Governador AM ATALAIA DO NORTE               5 1,023.00                 OMAR AZIZ
      Presidente MA TURIAÇU                        4   485.00                      LULA
      Governador AC JORDÃO                         3   386.00              MAILZA ASSIS
                 AM BARREIRINHA                    3   685.00                 OMAR AZIZ
                    BENJAMIN CONSTANT              3   677.00                 OMAR AZIZ
                    SÃO GABRIEL DA CACHOEIRA       3   523.00                 OMAR AZIZ
                    SANTA ISABEL DO RIO NEGRO      3   554.00                 OMAR AZIZ
      Presidente PA ORIXIMINÁ                      3   320.00                      LULA
1     Presidente RR UIRAMUTÃ                       3   428.00                      LULA
2     Presidente TO GOIATINS                       3   444.00                      LULA
                 AM SANTA ISABEL DO RIO NEGRO      3   537.00                      LULA
                    TABATINGA                      2   692.00                      LULA
                 MA SERRANO DO MARANHÃO            2   157.00                      LULA
                    SANTA HELENA                   2   109.00                      LULA
1     Presidente PA NOVO REPARTIMENTO              2   278.00                      LULA
2     Presidente MA PRIMEIRA CRUZ                  2    84.00                      LULA
                 AC JORDÃO                         2   249.00                      LULA
      Governador AM AMATURÁ                        2   272.00                 OMAR AZIZ
      Presidente PA ALTAMIRA                       2    87.00                      LULA
                 MA ALCÂNTARA                      2   123.00                      LULA
      Governador AM SÃO PAULO DE OLIVENÇA          2   491.00                 OMAR AZIZ
      Presidente AM BENJAMIN CONSTANT              2   469.00                      LULA
                    MAUÉS                          2   456.00                      LULA
                    PARINTINS                      2   308.00                      LULA
                    SANTO ANTÔNIO DO IÇÁ           2   644.00                      LULA
1     Presidente PA ALTAMIRA                       2    75.00                      LULA
2     Presidente AM SÃO PAULO DE OLIVENÇA          2   542.00                      LULA
                 RS VIAMÃO                         2   104.00                      LULA
                 TO TOCANTINÓPOLIS                 2   214.00                      LULA
1     Presidente MA SANTA HELENA                   2   103.00                      LULA
      Governador PA ALTAMIRA                       2    70.00              HANA GHASSAN
                    NOVO REPARTIMENTO              2   273.00              HANA GHASSAN
                    PARAUAPEBAS                    2   271.00              HANA GHASSAN
2     Presidente PA PARAUAPEBAS                    2   409.00                      LULA
                    SÃO FÉLIX DO XINGU             2   418.00                      LULA
1     Presidente AM SÃO GABRIEL DA CACHOEIRA       2   373.00                      LULA
      Governador PA SÃO FÉLIX DO XINGU             2   277.00  DR. DANIEL, HANA GHASSAN
2     Presidente PA AVEIRO                         1   106.00                      LULA
                 MA BARREIRINHAS                   1    95.00                      LULA
                 RR CAROEBE                        1    44.00                      LULA
                 RO PORTO VELHO                    1   104.00                      LULA
                 RS CÂNDIDO GODÓI                  1    82.00          FLAVIO BOLSONARO
                 MA CURURUPU                       1    54.00                      LULA
                 RS ARROIO DO PADRE                1   116.00          FLAVIO BOLSONARO
                 CE AQUIRAZ                        1    32.00                      LULA
                 ES ARACRUZ                        1    41.00                      LULA
                 CE PORANGA                        1    54.00                      LULA
                 MA MARANHÃOZINHO                  1   176.00                      LULA
                 BA ÉRICO CARDOSO                  1    44.00                      LULA
                    SENTO SÉ                       1    62.00                      LULA
                    IAÇU                           1    40.00                      LULA
                    BARRA DO MENDES                1    69.00                      LULA
                 AM URUCURITUBA                    1   101.00                      LULA
                 TO PARANÃ                         1    33.00                      LULA
                 MA GRAJAÚ                         1   102.00                      LULA
                 PR ORTIGUEIRA                     1   314.00                      LULA
                 MA MONTES ALTOS                   1   298.00                      LULA
                 PA MOJU                           1    41.00                      LULA
                    ALMEIRIM                       1   156.00                      LULA
                    ALENQUER                       1    60.00                      LULA
                 MT PORTO ALEGRE DO NORTE          1    61.00                      LULA
                    PEIXOTO DE AZEVEDO             1   179.00                      LULA
                 PA CHAVES                         1    48.00          FLAVIO BOLSONARO
                 MT GUARANTÃ DO NORTE              1   145.00                      LULA
                    CONFRESA                       1   309.00                      LULA
                    BARRA DO GARÇAS                1   119.00                      LULA
                 PA JACAREACANGA                   1    50.00          FLAVIO BOLSONARO
                 MG SALINAS                        1    47.00                      LULA
                 PI TERESINA                       1    16.00                      LULA
                 MG LUISLÂNDIA                     1    69.00                      LULA
                 PA NOVO REPARTIMENTO              1    18.00                      LULA
                 MA ÁGUA DOCE DO MARANHÃO          1   189.00                      LULA
                    VIANA                          1   100.00                      LULA
                 PA PARAGOMINAS                    1    54.00                      LULA
                 MA SÃO BENTO                      1    96.00                      LULA
                 PA VISEU                          1    64.00                      LULA
                 PB SAPÉ                           1    10.00                      LULA
                 PE FLORESTA                       1   227.00                      LULA
                 MS ARAL MOREIRA                   1    56.00                      LULA
1     Governador ES ARACRUZ                        1    31.00            HELDER SALOMÃO
2     Presidente AM JURUÁ                          1   149.00                      LULA
                    JAPURÁ                         1   224.00                      LULA
1     Presidente MG SALINAS                        1    41.00                      LULA
                    PORTEIRINHA                    1    26.00                      LULA
                    LUISLÂNDIA                     1    74.00                      LULA
                 MA MONTES ALTOS                   1   281.00                      LULA
                    GRAJAÚ                         1    95.00                      LULA
                    ALCÂNTARA                      1    77.00                      LULA
                 ES ARACRUZ                        1    33.00                      LULA
                 CE TAMBORIL                       1    92.00                      LULA
                    PORANGA                        1    54.00                      LULA
                 BA CAMAÇARI                       1    10.00                      LULA
                 AP MAZAGÃO                        1    81.00                      LULA
                 AM PARINTINS                      1    98.00                      LULA
                    BENJAMIN CONSTANT              1   242.00                      LULA
                 AC CRUZEIRO DO SUL                1   151.00                      LULA
      Governador SP SÃO PAULO                      1    41.00           FERNANDO HADDAD
                    SANTO ANDRÉ                    1    31.00           FERNANDO HADDAD
                    ITAPETININGA                   1    14.00                  TARCÍSIO
                    GUARULHOS                      1    11.00           FERNANDO HADDAD
                    DIADEMA                        1    12.00           FERNANDO HADDAD
                 RS VIAMÃO                         1    59.00           JULIANA BRIZOLA
                 PI BURITI DOS MONTES              1    72.00           RAFAEL FONTELES
                 PB SAPÉ                           1     5.00             LUCAS RIBEIRO
                 PA AVEIRO                         1    92.00              HANA GHASSAN
                 MT CONFRESA                       1   290.00           DOUTORA NATASHA
                 MS ARAL MOREIRA                   1    51.00                FÁBIO TRAD
      Presidente MS ARAL MOREIRA                   1    52.00                      LULA
                 MT PORTO ALEGRE DO NORTE          1    61.00                      LULA
                 PA ALMEIRIM                       1   156.00                      LULA
2     Governador AM CANUTAMA                       1    61.00                 OMAR AZIZ
      Presidente AM CARAUARI                       1   113.00                      LULA
                    BARREIRINHA                    1   261.00                      LULA
1     Governador MG ITURAMA                        1    13.00         CLEITINHO AZEVEDO
2     Presidente AC CRUZEIRO DO SUL                1   137.00                      LULA
      Governador ES ARACRUZ                        1    40.00           RICARDO FERRAÇO
                 AM TABATINGA                      1   347.00                 OMAR AZIZ
                    SANTO ANTÔNIO DO IÇÁ           1   283.00                 OMAR AZIZ
                    NOVA OLINDA DO NORTE           1   110.00                 OMAR AZIZ
                    MAUÉS                          1   121.00                 OMAR AZIZ
                    JAPURÁ                         1   226.00                 OMAR AZIZ
                    CARAUARI                       1   113.00                 OMAR AZIZ
1     Senador    RR ALTO ALEGRE                    1   108.00          HELENA DA ASATUR
      Presidente PA AVEIRO                         1   102.00                      LULA
                 ZZ TRÍPOLI                        1     2.00                      LULA
                    PORTO PRÍNCIPE                 1     5.00                      LULA
                 TO TOCANTINÓPOLIS                 1   159.00                      LULA
                    PARANÃ                         1    37.00                      LULA
                 RS VIAMÃO                         1    65.00                      LULA
                    CÂNDIDO GODÓI                  1    81.00          FLAVIO BOLSONARO
                 PA VISEU                          1    68.00                      LULA
                    PARAUAPEBAS                    1   141.00                      LULA
                    ORIXIMINÁ                      1   144.00                      LULA
                    JURUTI                         1    30.00                      LULA
                    JACAREACANGA                   1    49.00          FLAVIO BOLSONARO
2     Presidente TO TOCANTÍNIA                     1   196.00                      LULA

In [16]:
print('Detalhe — urnas com candidato único (maiores primeiro)')
unico.sort_values('comparecimento', ascending=False).reset_index(drop=True)

Detalhe — urnas com candidato único (maiores primeiro)

     turno  uf         municipio  zona  secao  local_votacao       cargo      candidato partido  votos_nominais  brancos  nulos  aptos  comparecimento  nr_urna
0        2  AM         TABATINGA    36     61           1201  Governador      OMAR AZIZ     PSD          347.00     0.00  18.00    400             365  2332683
1        2  AM         TABATINGA    36     61           1201  Presidente           LULA      PT          354.00     0.00  11.00    400             365  2332683
2        2  AM         TABATINGA    36     96           1260  Presidente           LULA      PT          338.00     0.00   9.00    388             347  2352217
3        2  AM             MAUÉS     5    176           1406  Presidente           LULA      PT          333.00     0.00   4.00    382             337  2341225
4        2  AM  ATALAIA DO NORTE    42     29           1112  Presidente           LULA      PT          325.00     1.00   9.00    441             335  2354152
..     ...  ..               ...   ...    ...            ...         ...            ...     ...             ...      ...    ...    ...             ...      ...
199      1  PB              SAPÉ     4    290           1597  Governador  LUCAS RIBEIRO      PP            5.00     3.00   5.00     21              13  2455215
200      1  BA          CAMAÇARI   171    409           1589  Presidente           LULA      PT           10.00     0.00   0.00     24              10  1754593
201      2  PB              SAPÉ     4    290           1597  Presidente           LULA      PT           10.00     0.00   0.00     21              10  2455215
202      1  ZZ    PORTO PRÍNCIPE     1    353           1015  Presidente           LULA      PT            5.00     0.00   0.00     33               5  1808076
203      1  ZZ           TRÍPOLI     1    443           1015  Presidente           LULA      PT            2.00     0.00   0.00     30               2  1808076

[204 rows x 15 columns]

## 5. Variação de votos totais por urna e por cidade (1º × 2º turno)

“Votos totais” = **comparecimento** da urna (todos os eleitores que votaram, incluindo brancos e nulos).
A chave da urna é `UF + município + zona + seção`.

- **5.1** — cidades cuja soma de votos variou mais de 10% entre os turnos;
- **5.2** — urnas individuais que variaram mais de 10%;
- **5.3** — urnas presentes em apenas um dos turnos;
- **5.4** (complementar) — dispersão do nº de votos entre as urnas de uma mesma cidade, por turno.

In [17]:
_ = con.execute('''
    CREATE OR REPLACE TEMP TABLE var_urna AS
    SELECT coalesce(a.uf, b.uf) AS uf, coalesce(a.cd_municipio, b.cd_municipio) AS cd_municipio,
           coalesce(a.municipio, b.municipio) AS municipio,
           coalesce(a.zona, b.zona) AS zona, coalesce(a.secao, b.secao) AS secao,
           a.aptos AS aptos_t1, b.aptos AS aptos_t2,
           a.comparecimento AS votos_t1, b.comparecimento AS votos_t2,
           b.comparecimento - a.comparecimento AS diferenca,
           (b.comparecimento - a.comparecimento) / nullif(a.comparecimento, 0) AS variacao,
           a.nr_urna AS urna_t1, b.nr_urna AS urna_t2
    FROM secoes_t1 a FULL OUTER JOIN secoes_t2 b USING (uf, cd_municipio, zona, secao)
''')

var_cidade = q(f'''
    SELECT uf, cd_municipio, municipio,
           count(*) FILTER (WHERE votos_t1 IS NOT NULL AND votos_t2 IS NOT NULL) AS urnas,
           sum(votos_t1) AS votos_t1, sum(votos_t2) AS votos_t2,
           sum(votos_t2) - sum(votos_t1) AS diferenca,
           round(100.0 * (sum(votos_t2) - sum(votos_t1)) / nullif(sum(votos_t1), 0), 2) AS variacao_pct,
           count(*) FILTER (WHERE abs(variacao) > {LIMIAR_VARIACAO}) AS urnas_var_acima_10pct,
           round(100.0 * count(*) FILTER (WHERE abs(variacao) > {LIMIAR_VARIACAO})
                 / count(*) FILTER (WHERE variacao IS NOT NULL), 2) AS pct_urnas_acima_10pct,
           round(100.0 * min(variacao), 2) AS menor_var_urna_pct,
           round(100.0 * max(variacao), 2) AS maior_var_urna_pct
    FROM var_urna
    GROUP BY ALL
    ORDER BY abs(variacao_pct) DESC
''')
print(f'{len(var_cidade):,} municípios comparados')
var_cidade.describe()

5,716 municípios comparados

       cd_municipio     urnas     votos_t1     votos_t2  diferenca  variacao_pct  urnas_var_acima_10pct  pct_urnas_acima_10pct  menor_var_urna_pct  maior_var_urna_pct
count      5,716.00  5,716.00     5,716.00     5,715.00   5,715.00      5,715.00               5,716.00               5,715.00            5,715.00            5,715.00
mean      51,054.06     87.33    21,916.70    22,438.51     517.98          1.85                   2.20                   3.97               -4.69                8.49
std       29,236.50    459.74   124,376.42   128,881.66   4,716.81          3.66                  13.03                  12.62                6.30                5.28
min           19.00      0.00         2.00         7.00 -19,220.00        -28.76                   0.00                   0.00              -89.41              -15.61
25%       24,989.50     17.00     3,747.00     3,809.00      24.00          0.67                   0.00                   0.00               -6.32                5.65
50%       49,985.50     31.00     7,110.50     7,226.00     137.00          2.38                   0.00                   0.00               -3.36                8.11
75%       78,658.00     65.00    15,087.50    15,464.50     381.50          3.52                   1.00                   2.86               -1.47               10.80
max       99,511.00 26,683.00 7,006,411.00 7,284,071.00 277,660.00         60.00                 569.00                 100.00               60.00               94.74

### 5.1 Cidades com variação total > 10% entre os turnos

In [18]:
cidades_10 = var_cidade[var_cidade.variacao_pct.abs() > LIMIAR_VARIACAO * 100].reset_index(drop=True)
print(f'{len(cidades_10):,} municípios com |variação| > {LIMIAR_VARIACAO:.0%}')
cidades_10

114 municípios com |variação| > 10%

     uf  cd_municipio                municipio  urnas  votos_t1  votos_t2  diferenca  variacao_pct  urnas_var_acima_10pct  pct_urnas_acima_10pct  menor_var_urna_pct  maior_var_urna_pct
0    ZZ         30333           PORTO PRÍNCIPE      1      5.00      8.00       3.00         60.00                      1                 100.00               60.00               60.00
1    ZZ         30805               WELLINGTON      5    339.00    526.00     187.00         55.16                      5                 100.00               20.00               94.74
2    ZZ         30295          PASO LOS LIBRES      1      5.00      7.00       2.00         40.00                      1                 100.00               40.00               40.00
3    ZZ         30848                   XANGAI      1    197.00    264.00      67.00         34.01                      1                 100.00               34.01               34.01
4    AP          6041                  ITAUBAL     31  7,354.00  5,239.00  -2,115.00        -28.76                     31                 100.00              -47.18              -14.97
5    AP          6068                   CUTIAS     23  5,191.00  3,758.00  -1,433.00        -27.61                     23                 100.00              -46.93              -15.61
6    AC          1066             PORTO WALTER     34  6,520.00  4,792.00  -1,728.00        -26.50                     34                 100.00              -48.40              -12.18
7    ZZ         30325            PORT OF SPAIN      1     19.00     24.00       5.00         26.32                      1                 100.00               26.32               26.32
8    ZZ         30740                 VARSÓVIA      1    291.00    363.00      72.00         24.74                      1                 100.00               24.74               24.74
9    AC          1040     MARECHAL THAUMATURGO     47  9,352.00  7,051.00  -2,301.00        -24.60                     42                  89.36              -50.22               -2.74
10   AP          6009                 PRACUÚBA     16  3,313.00  2,510.00    -803.00        -24.24                     16                 100.00              -43.97              -12.20
11   AP          6114           FERREIRA GOMES     26  6,260.00  4,764.00  -1,496.00        -23.90                     26                 100.00              -33.87              -13.33
12   ZZ         30619                 TEL AVIV      5    730.00    902.00     172.00         23.56                      5                 100.00               19.05               31.58
13   ZZ         29351                BARCELONA     22  5,185.00  6,381.00   1,196.00         23.07                     22                 100.00               12.90               36.84
14   ZZ         29840                  JACARTA      1     31.00     38.00       7.00         22.58                      1                 100.00               22.58               22.58
15   ZZ         30902                 HARTFORD     12  1,951.00  2,378.00     427.00         21.89                     12                 100.00               12.21               31.94
16   ZZ         99503                EDIMBURGO      6    694.00    845.00     151.00         21.76                      5                  83.33               -0.70               49.04
17   ZZ         30228                NOVA YORK     53 10,134.00 12,241.00   2,107.00         20.79                     51                  96.23                9.51               40.56
18   ZZ         30244                     OSLO      3    909.00  1,097.00     188.00         20.68                      3                 100.00               15.87               25.44
19   AP          6017                    AMAPÁ     27  6,262.00  4,971.00  -1,291.00        -20.62                     27                 100.00              -27.75              -13.39
20   ZZ         29254                   ABIDJÃ      1     44.00     53.00       9.00         20.45                      1                 100.00               20.45               20.45
21   ZZ         30651                   CANTÃO      1     99.00    119.00      20.00         20.20                      1                 100.00               20.20               20.20
22   ZZ         30562                   SYDNEY     19  5,694.00  6,830.00   1,136.00         19.95                     18                  94.74                8.08               41.98
23   ZZ         99511                 MARSELHA      4    875.00  1,049.00     174.00         19.89                      4                 100.00               15.55               25.65
24   AP          6173          TARTARUGALZINHO     44  9,274.00  7,484.00  -1,790.00        -19.30                     42                  95.45              -32.00               -7.87
25   ZZ         29980              LOS ANGELES     25  4,609.00  5,473.00     864.00         18.75                     21                  84.00                4.93               51.55
26   RR          3042                  AMAJARI     30  6,520.00  5,302.00  -1,218.00        -18.68                     29                  96.67              -26.73               -8.46
27   ZZ         29513                  CHICAGO     18  2,779.00  3,295.00     516.00         18.57                     14                  77.78                5.44               35.71
28   ZZ         30503            SÃO FRANCISCO     20  3,896.00  4,610.00     714.00         18.33                     19                  95.00                5.88               41.23
29   ZZ         30864                  ZURIQUE     19  6,001.00  7,086.00   1,085.00         18.08                     19                 100.00               11.47               29.04
30   AP          6076                  MAZAGÃO     90 18,989.00 15,596.00  -3,393.00        -17.87                     83                  92.22              -35.07               -6.17
31   AP          6106           SERRA DO NAVIO     12  3,040.00  2,499.00    -541.00        -17.80                     12                 100.00              -22.71              -12.58
32   ZZ         29416                   BOSTON     69 16,390.00 19,304.00   2,914.00         17.78                     67                  97.10                5.56               41.79
33   RR          3158                 SÃO LUIZ     25  5,114.00  4,207.00    -907.00        -17.74                     23                  92.00              -33.96               -5.38
34   AP          6033                 CALÇOENE     30  7,009.00  5,773.00  -1,236.00        -17.63                     30                 100.00              -31.15              -10.68
35   RR          3026                  IRACEMA     30  6,153.00  5,106.00  -1,047.00        -17.02                     28                  93.33              -38.69               -8.72
36   ZZ         30180                  MUNIQUE     21  5,423.00  6,316.00     893.00         16.47                     18                  85.71                4.81               34.08
37   RR          3034                CARACARAÍ     62 12,452.00 10,420.00  -2,032.00        -16.32                     59                  95.16              -34.28               -4.59
38   ZZ         29556          CIUDAD DEL ESTE      7  2,586.00  3,001.00     415.00         16.05                      6                  85.71                9.78               19.94
39   ZZ         99180                   NASSAU      1     19.00     22.00       3.00         15.79                      1                 100.00               15.79               15.79
40   ZZ         29343                  BANGKOK      1    102.00    118.00      16.00         15.69                      1                 100.00               15.69               15.69
41   AC          1473                 TARAUACÁ    110 22,603.00 19,112.00  -3,491.00        -15.44                     90                  81.82              -39.57                1.26
42   AC          1457           SENA MADUREIRA    120 24,661.00 20,888.00  -3,773.00        -15.30                    101                  84.17              -57.24                1.90
43   ZZ         29955                   LISBOA    103 28,643.00 33,002.00   4,359.00         15.22                     92                  89.32                5.79               42.25
44   MA          8850            PRIMEIRA CRUZ     46  9,220.00  7,817.00  -1,403.00        -15.22                     32                  69.57              -31.94                1.28
45   RR          3131       SÃO JOÃO DA BALIZA     23  4,843.00  4,112.00    -731.00        -15.09                     21                  91.30              -21.52               -6.45
46   ZZ         30961                     FARO     11  2,761.00  3,176.00     415.00         15.03                     10                  90.91                6.89               25.28
47   ZZ         29483                    CAIRO      1     69.00     79.00      10.00         14.49                      1                 100.00               14.49               14.49
48   AC          1082          RODRIGUES ALVES     55 10,218.00  8,741.00  -1,477.00        -14.45                     44                  80.00              -31.61               -1.83
49   ZZ         29335                   ATENAS      2    508.00    581.00      73.00         14.37                      2                 100.00               12.35               16.34
50   AP          6084  PEDRA BRANCA DO AMAPARI     31  7,119.00  6,098.00  -1,021.00        -14.34                     28                  90.32              -21.78               -0.41
51   ZZ         99473                   BAREIN      1     49.00     42.00      -7.00        -14.29                      1                 100.00              -14.29              -14.29
52   AP          6122          VITÓRIA DO JARI     41  8,071.00  6,924.00  -1,147.00        -14.21                     33                  80.49              -28.78               -6.04
53   ZZ         30163                   MOSCOU      1     85.00     97.00      12.00         14.12                      1                 100.00               14.12               14.12
54   MA          8109   PORTO RICO DO MARANHÃO     29  5,325.00  4,582.00    -743.00        -13.95                     20                  68.97              -33.77               -2.15
55   ZZ         30112                    MIAMI     51 12,278.00 13,991.00   1,713.00         13.95                     43                  84.31                3.74               26.29
56   ZZ         29580               CONCEPCIÓN      1     36.00     31.00      -5.00        -13.89                      1                 100.00              -13.89              -13.89
57   ZZ         30465         SALTO DEL GUAIRÁ      2    537.00    611.00      74.00         13.78                      2                 100.00               11.95               17.01
58   ZZ         39080                  ATLANTA     22  5,022.00  5,707.00     685.00         13.64                     18                  81.82                6.75               24.57
59   ZZ         30120                    MILÃO     37  7,455.00  8,465.00   1,010.00         13.55                     26                  70.27                0.00               27.46
60   ZZ         39020                   ZAGREB      1     52.00     59.00       7.00         13.46                      1                 100.00               13.46               13.46
61   ZZ         29971                  LONDRES     48 14,797.00 16,781.00   1,984.00         13.41                     36                  75.00                3.05               25.11
62   MA          7994                    ICATU     96 19,268.00 16,685.00  -2,583.00        -13.41                     64                  66.67              -37.11               -3.78
63   RR          3050              ALTO ALEGRE     50 11,347.00  9,830.00  -1,517.00        -13.37                     40                  80.00              -28.07                0.00
64   AM         98396                MANAQUIRI     46 11,733.00 10,178.00  -1,555.00        -13.25                     34                  73.91              -21.88               -2.44
65   ZZ         30635                  TORONTO     28  8,999.00 10,190.00   1,191.00         13.23                     21                  75.00                0.40               23.20
66   MA          8249  SANTO AMARO DO MARANHÃO     49 10,920.00  9,480.00  -1,440.00        -13.19                     35                  71.43              -30.70               -1.09
67   PA          4219                    BAGRE     54 13,159.00 11,435.00  -1,724.00        -13.10                     40                  74.07              -26.46               -1.56
68   AC          1104                   JORDÃO     24  4,514.00  3,925.00    -589.00        -13.05                     14                  58.33              -43.90                1.53
69   ZZ         30406                    RABAT      1     47.00     41.00      -6.00        -12.77                      1                 100.00              -12.77              -12.77
70   AP          6025             PORTO GRANDE     45 12,338.00 10,766.00  -1,572.00        -12.74                     37                  82.22              -21.72               -6.12
71   ZZ         30341                    PORTO     62 20,279.00 22,862.00   2,583.00         12.74                     42                  67.74                4.39               30.61
72   ZZ         29777                   HAVANA      1     40.00     45.00       5.00         12.50                      1                 100.00               12.50               12.50
73   ZZ         30287                    PARIS     34 10,540.00 11,854.00   1,314.00         12.47                     24                  70.59                3.87               37.41
74   ZZ         30783               WASHINGTON     31  4,836.00  5,437.00     601.00         12.43                     19                  61.29                0.00               27.20
75   PA          4499                   CHAVES     63 11,487.00 10,065.00  -1,422.00        -12.38                     39                  61.90              -23.50                0.63
76   RR          3123                PACARAIMA     42  8,084.00  7,085.00    -999.00        -12.36                     29                  69.05              -21.36               -2.34
77   MS         98159                   TACURU     22  4,663.00  5,234.00     571.00         12.25                     15                  68.18                8.45               21.21
78   ZZ         30546                    SÓFIA      1     49.00     55.00       6.00         12.24                      1                 100.00               12.24               12.24
79   ZZ         29696                FRANKFURT     21  5,619.00  6,305.00     686.00         12.21                     13                  61.90                5.80               19.53
80   ZZ         99490                  ORLANDO     34  8,994.00 10,090.00   1,096.00         12.19                     28                  82.35                2.58               20.37
81   ZZ         29912                    LAGOS      1     33.00     37.00       4.00         12.12                      1                 100.00               12.12               12.12
82   ZZ         30597                    TEERÃ      1     25.00     28.00       3.00         12.00                      1                 100.00               12.00               12.00
83   RR          3069                    CANTÁ     72 14,635.00 12,893.00  -1,742.00        -11.90                     46                  63.89              -28.09               -3.38
84   ZZ         29467             BUENOS AIRES     15  5,435.00  6,082.00     647.00         11.90                      9                  60.00                5.20               24.00
85   RR          3085             RORAINÓPOLIS     96 19,054.00 16,800.00  -2,254.00        -11.83                     52                  54.17              -46.67                7.41
86   RR          3093                  MUCAJAÍ     61 12,003.00 10,600.00  -1,403.00        -11.69                     40                  65.57              -24.00               -4.29
87   RR          3077                   BONFIM     49 10,091.00  8,911.00  -1,180.00        -11.69                     30                  61.22              -23.56               -1.96
88   AP          6092                 OIAPOQUE     91 17,516.00 15,482.00  -2,034.00        -11.61                     58                  63.74              -32.86               -0.41
89   AM          2992               CAAPIRANGA     26  7,067.00  6,259.00    -808.00        -11.43                     15                  57.69              -24.24               -2.77
90   MS         90115                  AMAMBAI     96 18,880.00 21,037.00   2,157.00         11.42                     38                  39.58                0.55               45.83
91   ZZ         30155                 MONTREAL     15  6,101.00  6,795.00     694.00         11.38                     11                  73.33                6.28               26.88
92   RR          3115                NORMANDIA     42  8,367.00  7,416.00    -951.00        -11.37                     22                  52.38              -64.38                5.63
93   AC          1090              MÂNCIO LIMA     57 12,089.00 10,732.00  -1,357.00        -11.23                     25                  43.86              -37.82               -2.02
94   AC          1015                 CAPIXABA     34  6,513.00  5,785.00    -728.00        -11.18                     22                  64.71              -20.48               -3.55
95   ZZ         30066                    MADRI     30  6,833.00  7,591.00     758.00         11.09                     18                  60.00                1.29               42.37
96   ZZ         30414                 RAMALLAH      3  1,202.00  1,069.00    -133.00        -11.06                      1                  33.33              -18.76               -2.82
97   AL         27774                   JUNDIÁ     14  3,815.00  3,402.00    -413.00        -10.83                      6                  42.86              -31.49                0.43
98   AC          1139                    FEIJÓ     88 18,156.00 16,190.00  -1,966.00        -10.83                     36                  40.91              -38.33                0.00
99   ZZ         29394                   BISSAU      1     37.00     41.00       4.00         10.81                      1                 100.00               10.81               10.81
100  MA          9415                  TURIAÇU    118 22,760.00 20,310.00  -2,450.00        -10.76                     56                  47.46              -32.56                2.78
101  PI         11258              MIGUEL LEÃO      7  1,630.00  1,455.00    -175.00        -10.74                      5                  71.43              -17.81               -6.78
102  ZZ         39063                VANCOUVER     16  5,912.00  6,543.00     631.00         10.67                      9                  56.25                3.24               23.65
103  ZZ         29645                     DÍLI      1     47.00     52.00       5.00         10.64                      1                 100.00               10.64               10.64
104  ZZ         29700                  GENEBRA     15  5,237.00  5,790.00     553.00         10.56                     10                  66.67                5.99               17.24
105  ZZ         99430         KINGSTON-JAMAICA      1     19.00     17.00      -2.00        -10.53                      1                 100.00              -10.53              -10.53
106  ZZ         39102                  MASCATE      1     38.00     34.00      -4.00        -10.53                      1                 100.00              -10.53              -10.53

In [19]:
print('Cidades com maior proporção de urnas que variaram > 10%')
var_cidade[var_cidade.urnas >= 5].sort_values('pct_urnas_acima_10pct', ascending=False).head(50).reset_index(drop=True)

Cidades com maior proporção de urnas que variaram > 10%

    uf  cd_municipio                municipio  urnas  votos_t1  votos_t2  diferenca  variacao_pct  urnas_var_acima_10pct  pct_urnas_acima_10pct  menor_var_urna_pct  maior_var_urna_pct
0   ZZ         30805               WELLINGTON      5    339.00    526.00     187.00         55.16                      5                 100.00               20.00               94.74
1   ZZ         30619                 TEL AVIV      5    730.00    902.00     172.00         23.56                      5                 100.00               19.05               31.58
2   AP          6106           SERRA DO NAVIO     12  3,040.00  2,499.00    -541.00        -17.80                     12                 100.00              -22.71              -12.58
3   AP          6017                    AMAPÁ     27  6,262.00  4,971.00  -1,291.00        -20.62                     27                 100.00              -27.75              -13.39
4   AP          6033                 CALÇOENE     30  7,009.00  5,773.00  -1,236.00        -17.63                     30                 100.00              -31.15              -10.68
5   ZZ         30902                 HARTFORD     12  1,951.00  2,378.00     427.00         21.89                     12                 100.00               12.21               31.94
6   ZZ         30864                  ZURIQUE     19  6,001.00  7,086.00   1,085.00         18.08                     19                 100.00               11.47               29.04
7   ZZ         29351                BARCELONA     22  5,185.00  6,381.00   1,196.00         23.07                     22                 100.00               12.90               36.84
8   AP          6114           FERREIRA GOMES     26  6,260.00  4,764.00  -1,496.00        -23.90                     26                 100.00              -33.87              -13.33
9   AP          6009                 PRACUÚBA     16  3,313.00  2,510.00    -803.00        -24.24                     16                 100.00              -43.97              -12.20
10  AP          6041                  ITAUBAL     31  7,354.00  5,239.00  -2,115.00        -28.76                     31                 100.00              -47.18              -14.97
11  AC          1066             PORTO WALTER     34  6,520.00  4,792.00  -1,728.00        -26.50                     34                 100.00              -48.40              -12.18
12  AP          6068                   CUTIAS     23  5,191.00  3,758.00  -1,433.00        -27.61                     23                 100.00              -46.93              -15.61
13  ZZ         29416                   BOSTON     69 16,390.00 19,304.00   2,914.00         17.78                     67                  97.10                5.56               41.79
14  RR          3042                  AMAJARI     30  6,520.00  5,302.00  -1,218.00        -18.68                     29                  96.67              -26.73               -8.46
15  ZZ         30228                NOVA YORK     53 10,134.00 12,241.00   2,107.00         20.79                     51                  96.23                9.51               40.56
16  AP          6173          TARTARUGALZINHO     44  9,274.00  7,484.00  -1,790.00        -19.30                     42                  95.45              -32.00               -7.87
17  RR          3034                CARACARAÍ     62 12,452.00 10,420.00  -2,032.00        -16.32                     59                  95.16              -34.28               -4.59
18  ZZ         30503            SÃO FRANCISCO     20  3,896.00  4,610.00     714.00         18.33                     19                  95.00                5.88               41.23
19  ZZ         30562                   SYDNEY     19  5,694.00  6,830.00   1,136.00         19.95                     18                  94.74                8.08               41.98
20  RR          3026                  IRACEMA     30  6,153.00  5,106.00  -1,047.00        -17.02                     28                  93.33              -38.69               -8.72
21  AP          6076                  MAZAGÃO     90 18,989.00 15,596.00  -3,393.00        -17.87                     83                  92.22              -35.07               -6.17
22  RR          3158                 SÃO LUIZ     25  5,114.00  4,207.00    -907.00        -17.74                     23                  92.00              -33.96               -5.38
23  RR          3131       SÃO JOÃO DA BALIZA     23  4,843.00  4,112.00    -731.00        -15.09                     21                  91.30              -21.52               -6.45
24  ZZ         30961                     FARO     11  2,761.00  3,176.00     415.00         15.03                     10                  90.91                6.89               25.28
25  AP          6084  PEDRA BRANCA DO AMAPARI     31  7,119.00  6,098.00  -1,021.00        -14.34                     28                  90.32              -21.78               -0.41
26  AC          1040     MARECHAL THAUMATURGO     47  9,352.00  7,051.00  -2,301.00        -24.60                     42                  89.36              -50.22               -2.74
27  ZZ         29955                   LISBOA    103 28,643.00 33,002.00   4,359.00         15.22                     92                  89.32                5.79               42.25
28  ZZ         30180                  MUNIQUE     21  5,423.00  6,316.00     893.00         16.47                     18                  85.71                4.81               34.08
29  ZZ         29556          CIUDAD DEL ESTE      7  2,586.00  3,001.00     415.00         16.05                      6                  85.71                9.78               19.94
30  ZZ         30112                    MIAMI     51 12,278.00 13,991.00   1,713.00         13.95                     43                  84.31                3.74               26.29
31  AC          1457           SENA MADUREIRA    120 24,661.00 20,888.00  -3,773.00        -15.30                    101                  84.17              -57.24                1.90
32  ZZ         29980              LOS ANGELES     25  4,609.00  5,473.00     864.00         18.75                     21                  84.00                4.93               51.55
33  ZZ         99503                EDIMBURGO      6    694.00    845.00     151.00         21.76                      5                  83.33               -0.70               49.04
34  ZZ         99490                  ORLANDO     34  8,994.00 10,090.00   1,096.00         12.19                     28                  82.35                2.58               20.37
35  AP          6025             PORTO GRANDE     45 12,338.00 10,766.00  -1,572.00        -12.74                     37                  82.22              -21.72               -6.12
36  ZZ         39080                  ATLANTA     22  5,022.00  5,707.00     685.00         13.64                     18                  81.82                6.75               24.57
37  AC          1473                 TARAUACÁ    110 22,603.00 19,112.00  -3,491.00        -15.44                     90                  81.82              -39.57                1.26
38  AP          6122          VITÓRIA DO JARI     41  8,071.00  6,924.00  -1,147.00        -14.21                     33                  80.49              -28.78               -6.04
39  AC          1082          RODRIGUES ALVES     55 10,218.00  8,741.00  -1,477.00        -14.45                     44                  80.00              -31.61               -1.83
40  RR          3050              ALTO ALEGRE     50 11,347.00  9,830.00  -1,517.00        -13.37                     40                  80.00              -28.07                0.00
41  ZZ         29513                  CHICAGO     18  2,779.00  3,295.00     516.00         18.57                     14                  77.78                5.44               35.71
42  ZZ         29971                  LONDRES     48 14,797.00 16,781.00   1,984.00         13.41                     36                  75.00                3.05               25.11
43  ZZ         30635                  TORONTO     28  8,999.00 10,190.00   1,191.00         13.23                     21                  75.00                0.40               23.20
44  PA          4219                    BAGRE     54 13,159.00 11,435.00  -1,724.00        -13.10                     40                  74.07              -26.46               -1.56
45  AM         98396                MANAQUIRI     46 11,733.00 10,178.00  -1,555.00        -13.25                     34                  73.91              -21.88               -2.44
46  ZZ         30155                 MONTREAL     15  6,101.00  6,795.00     694.00         11.38                     11                  73.33                6.28               26.88
47  MA          8249  SANTO AMARO DO MARANHÃO     49 10,920.00  9,480.00  -1,440.00        -13.19                     35                  71.43              -30.70               -1.09
48  PI         11258              MIGUEL LEÃO      7  1,630.00  1,455.00    -175.00        -10.74                      5                  71.43              -17.81               -6.78
49  ZZ         30287                    PARIS     34 10,540.00 11,854.00   1,314.00         12.47                     24                  70.59                3.87               37.41

### 5.2 Urnas com variação > 10% entre os turnos

In [20]:
urnas_10 = q(f'''
    SELECT uf, municipio, zona, secao, aptos_t1, aptos_t2, votos_t1, votos_t2, diferenca,
           round(100.0 * variacao, 2) AS variacao_pct, urna_t1, urna_t2,
           urna_t1 <> urna_t2 AS urna_substituida
    FROM var_urna
    WHERE abs(variacao) > {LIMIAR_VARIACAO}
    ORDER BY abs(variacao) DESC
''')
print(f'{len(urnas_10):,} urnas com |variação| > {LIMIAR_VARIACAO:.0%} '
      f'(de {q("SELECT count(*) FROM var_urna WHERE variacao IS NOT NULL").iloc[0, 0]:,} comparáveis)')
display(urnas_10.groupby('uf').size().rename('urnas').to_frame().T)
urnas_10.head(200)

12,580 urnas com |variação| > 10% (de 499,205 comparáveis)

uf      AC   AL   AM   AP    BA   CE  DF  ES   GO   MA    MG   MS   MT   PA  PB   PE   PI   PR   RJ   RN  RO   RR   RS  SC  SE    SP  TO   ZZ
urnas  599  147  537  720  1607  223   9  59  109  648  1135  400  100  961  82  522  139  408  656  126  22  442  302  56  36  1684  41  810

     uf                  municipio  zona  secao  aptos_t1  aptos_t2  votos_t1  votos_t2  diferenca  variacao_pct  urna_t1  urna_t2  urna_substituida
0    ZZ                 WELLINGTON     1   1693       699       699        38        74         36         94.74  1664895  1664895             False
1    PR             INÁCIO MARTINS    34    133       215       215       170        18       -152        -89.41  2060731  2060731             False
2    ZZ                 WELLINGTON     1   1088       696       697        40        73         33         82.50  1652005  1652005             False
3    RJ                MANGARATIBA    54    140       131       131        89        18        -71        -79.78  2350559  2350559             False
4    PA                   ALTAMIRA    18    519        54        54        21        35         14         66.67  2432252  2432252             False
5    PA                PARAUAPEBAS   106    330       325       325       128       212         84         65.63  2191815  2191815             False
6    RR                  NORMANDIA     9     77       134       134        73        26        -47        -64.38  2260555  2260555             False
7    ZZ                 WELLINGTON     1   1690       700       700       101       163         62         61.39  1663973  1663973             False
8    ZZ             PORTO PRÍNCIPE     1    353        33        33         5         8          3         60.00  1808076  1808076             False
9    AC             SENA MADUREIRA     3    148       216       216       152        65        -87        -57.24  2047901  2047901             False
10   MS                   PARANHOS     1    179       242       242       100       157         57         57.00  2002843  2002843             False
11   MS                   PARANHOS     1    177       250       250        97       152         55         56.70  2001789  2001789             False
12   ZZ                   CAMBERRA     1    735       575       575        72       111         39         54.17  1811058  1811058             False
13   PA                PARAUAPEBAS   106    244       289       289       131       201         70         53.44  2199222  2199222             False
14   ZZ                LOS ANGELES     1    586       788       788        97       147         50         51.55  1673284  1673284             False
15   AC       MARECHAL THAUMATURGO     4    444       263       263       223       111       -112        -50.22  2269434  2269434             False
16   ZZ                  EDIMBURGO     1   3801       564       564       104       155         51         49.04  1666163  1666163             False
17   AC               PORTO WALTER     4    429       234       233       188        97        -91        -48.40  2260491  2260491             False
18   ZZ                  EDIMBURGO     1   3198       793       793        29        43         14         48.28  1680732  1680732             False
19   ZZ                 WELLINGTON     1   1691       699       699        85       126         41         48.24  1665080  1665080             False
20   AP                    ITAUBAL    10    459       281       281       195       103        -92        -47.18  2354384  2354384             False
21   MS                   DOURADOS    43    411       254       254       121       178         57         47.11  2334048  2334048             False
22   SP                    DRACENA   149    119        39        27        34        18        -16        -47.06  1789952  1789952             False
23   AP                     CUTIAS    10    458       235       235       179        95        -84        -46.93  2340907  2340907             False
24   AC       MARECHAL THAUMATURGO     4    294       271       270       237       126       -111        -46.84  2256772  2256772             False
25   RR               RORAINÓPOLIS     8     94       120       120       105        56        -49        -46.67  2288366  2288366             False
26   MA         HUMBERTO DE CAMPOS    32     35       190       190       156        84        -72        -46.15  2288747  2288747             False
27   MS                    AMAMBAI     1     52       304       304       120       175         55         45.83  2001842  2001842             False
28   AC       MARECHAL THAUMATURGO     4    223       270       270       232       127       -105        -45.26  2274449  2274449             False
29   AC       MARECHAL THAUMATURGO     4    162       262       260       225       124       -101        -44.89  2273101  2273101             False
30   AP                   PRACUÚBA     1     42       294       294       232       130       -102        -43.97  2019818  2019818             False
31   AC                     JORDÃO     5     62       158       156       123        69        -54        -43.90  2257027  2257027             False
32   AC       MARECHAL THAUMATURGO     4    324       244       242       206       116        -90        -43.69  2264518  2264518             False
33   AP                    ITAUBAL    10    461       277       277       211       119        -92        -43.60  2358719  2343260              True
34   SP               PRAIA GRANDE   406    368        38        27        30        17        -13        -43.33  2145460  2145460             False
35   RJ                MANGARATIBA    54    127       343       343       238       137       -101        -42.44  2436360  2436360             False
36   ZZ                      MADRI     1     76       792       793        59        84         25         42.37  1751076  1751076             False
37   AP                    ITAUBAL    10    464       289       289       222       128        -94        -42.34  2354082  2354082             False
38   ZZ                     LISBOA     1    538       775       775       187       266         79         42.25  1665721  1665721             False
39   BA                   CAMAÇARI   170    262       119        68       107        62        -45        -42.06  1767510  1767510             False
40   ZZ                     SYDNEY     1   1963       798       798       162       230         68         41.98  1672430  1672430             False
41   RJ                MANGARATIBA    54    126       326       326       255       148       -107        -41.96  2426264  2426264             False
42   ZZ                     BOSTON     1   1225       781       781       134       190         56         41.79  1650934  1650934             False
43   AC               PORTO WALTER     4    314       151       150       125        73        -52        -41.60  2280822  2280822             False
44   AP                    ITAUBAL    10    456       351       351       280       164       -116        -41.43  2355726  2355726             False
45   AM                 NOVO AIRÃO    34     20        73        73        58        34        -24        -41.38  2356459  2356459             False
46   AC            CRUZEIRO DO SUL     4    235       180       179       133        78        -55        -41.35  2256510  2256510             False
47   PR              PRUDENTÓPOLIS    30     37       339       339       264       155       -109        -41.29  2283216  2283216             False
48   ZZ              SÃO FRANCISCO     1   3029       789       788       114       161         47         41.23  1680760  1680760             False
49   AP                     CUTIAS    10    462       282       283       228       135        -93        -40.79  2355759  2355759             False
50   ZZ                  NOVA YORK     1    320       747       747       143       201         58         40.56  1667926  1667926             False
51   MS                    AMAMBAI     1     99       298       298       143       201         58         40.56  2022817  2022817             False
52   ZZ                     BOSTON     1    948       778       778       131       184         53         40.46  1681321  1681321             False
53   AP                    ITAUBAL    10      9       160       160       122        73        -49        -40.16  2340943  2340943             False
54   MS                    AMAMBAI     1    158       331       331       167       234         67         40.12  2023039  2023039             False
55   ZZ            PASO LOS LIBRES     1    348        41        41         5         7          2         40.00  1808076  1808076             False
56   MG              JOÃO PINHEIRO   151    194        42        39        30        18        -12        -40.00  2054899  2054899             False
57   AP                     CUTIAS    10    452        85        85        65        39        -26        -40.00  2354888  2354888             False
58   AC            CRUZEIRO DO SUL     4    422       181       181       118        71        -47        -39.83  2254352  2254352             False
59   AC       MARECHAL THAUMATURGO     4    201       261       261       234       141        -93        -39.74  2273387  2273387             False
60   AC                   TARAUACÁ     5     92       219       216       187       113        -74        -39.57  2256885  2256885             False
61   AC       MARECHAL THAUMATURGO     4    337       214       214       177       107        -70        -39.55  2251544  2251544             False
62   AP                    ITAUBAL    10    433       295       295       243       147        -96        -39.51  2358038  2358038             False
63   SP            TEODORO SAMPAIO   330    127       282       282       142       198         56         39.44  2362387  2362387             False
64   AC            CRUZEIRO DO SUL     4    229       293       292       208       126        -82        -39.42  2266075  2266075             False
65   AC            CRUZEIRO DO SUL     4    459       162       162       134        82        -52        -38.81  2278657  2278657             False
66   RR                    IRACEMA     6     97       272       272       199       122        -77        -38.69  2019210  2019210             False
67   PE                     OLINDA   117     16       220       136       210       129        -81        -38.57  2043828  2043828             False
68   MG                 ITAMBACURI   136    216        31        21        26        16        -10        -38.46  2081327  2081327             False
69   AC             SENA MADUREIRA     3     98       217       215       185       114        -71        -38.38  2045233  2045233             False
70   AC                      FEIJÓ     7     66       184       184       120        74        -46        -38.33  2261681  2261681             False
71   PR             INÁCIO MARTINS    34    117       203       203       170       105        -65        -38.24  2092245  2092245             False
72   AC                     JORDÃO     5     56       312       312       234       145        -89        -38.03  2269515  2269515             False
73   AP                    ITAUBAL    10    410       182       182       156        97        -59        -37.82  2469280  2469280             False
74   AC                MÂNCIO LIMA     4    218       156       156       119        74        -45        -37.82  2251813  2251813             False
75   AC                      FEIJÓ     7     47       271       271       209       130        -79        -37.80  2251812  2251812             False
76   RR               RORAINÓPOLIS     8     29       264       263       184       115        -69        -37.50  2294130  2294130             False
77   ZZ                      PARIS     1    807       788       789       147       202         55         37.41  1670571  1670571             False
78   ZZ                     SYDNEY     1   3007       790       791       313       430        117         37.38  1770958  1770958             False
79   MS                    AMAMBAI     1    191       293       293       169       232         63         37.28  2009642  2009642             False
80   AC       MARECHAL THAUMATURGO     4    375       298       297       234       147        -87        -37.18  2266279  2266279             False
81   MA                      ICATU    31    238       120       120        97        61        -36        -37.11  2311289  2311289             False
82   MG              BOA ESPERANÇA    43    132        30        21        27        17        -10        -37.04  2423286  2423286             False
83   AC                MÂNCIO LIMA     4    445       156       156       127        80        -47        -37.01  2273105  2273105             False
84   AC       MARECHAL THAUMATURGO     4    160       296       295       238       150        -88        -36.97  2266411  2266411             False
85   AC            CRUZEIRO DO SUL     4    296       228       226       176       111        -65        -36.93  2294261  2294261             False
86   ZZ                  BARCELONA     1   1570       797       799       152       208         56         36.84  1785772  1785772             False
87   PE                     OLINDA   117    417       222       139       201       127        -74        -36.82  2195271  2195271             False
88   AP                     CUTIAS    10    416       260       260       204       129        -75        -36.76  2358864  2358613              True
89   AC               PORTO WALTER     4    320       237       237       215       136        -79        -36.74  2270299  2270299             False
90   AP                    ITAUBAL    10    376       356       356       286       181       -105        -36.71  2341436  2341436             False
91   PA                PARAUAPEBAS   106    365       289       289       145       198         53         36.55  2183419  2183419             False
92   ZZ                     BOSTON     1   1388       787       787       141       192         51         36.17  1676268  1676268             False
93   AC               PORTO WALTER     4    166       225       224       188       120        -68        -36.17  2264530  2264530             False
94   AC             SENA MADUREIRA     3    149       170       168       144        92        -52        -36.11  2045093  2045093             False
95   ZZ                  NOVA YORK     1    296       745       745       150       204         54         36.00  1671449  1671449             False
96   ZZ                  NOVA YORK     1    310       746       748       178       242         64         35.96  1668222  1668222             False
97   ZZ                    CHICAGO     1    645       738       736       112       152         40         35.71  1672558  1672558             False
98   AM  SANTA ISABEL DO RIO NEGRO    30     30       167       167        56        76         20         35.71  2460506  2460506             False
99   ZZ                  NOVA YORK     1    297       745       745       115       156         41         35.65  1678452  1678452             False
100  SC                   CRICIÚMA    98    216        46        33        31        20        -11        -35.48  2375794  2375794             False
101  AP                     MACAPÁ    10    244       222       222       192       124        -68        -35.42  2342511  2342511             False
102  RR                    CAROEBE     4    141        80        80        68        44        -24        -35.29  2283087  2283087             False
103  AP                    MAZAGÃO     5     80       313       313       268       174        -94        -35.07  2029834  2029834             False
104  AP                     MACAPÁ    10    428       225       225       197       128        -69        -35.03  2343966  2343966             False
105  RR                    IRACEMA     6     79       276       276       193       126        -67        -34.72  2275343  2275343             False
106  AP                    ITAUBAL    10    429       293       293       228       149        -79        -34.65  2356442  2356442             False
107  AC       MARECHAL THAUMATURGO     4    143       205       203       157       103        -54        -34.39  2280866  2280866             False
108  AC               PORTO WALTER     4    477       272       272       207       136        -71        -34.30  2291272  2291272             False
109  RR                  CARACARAÍ     2     92       323       323       283       186        -97        -34.28  2257705  2257705             False
110  AM                URUCURITUBA     3    251        98        98        76        50        -26        -34.21  2359896  2359896             False
111  ZZ              SÃO FRANCISCO     1   1028       789       789       120       161         41         34.17  1653507  1653507             False
112  AP                    ITAUBAL    10    351       354       354       281       185        -96        -34.16  2340940  2340940             False
113  ZZ                    MUNIQUE     1    119       640       641       223       299         76         34.08  1808518  1808518             False
114  ZZ                  NOVA YORK     1    299       745       745       135       181         46         34.07  1668287  1668287             False
115  PA                     GURUPÁ    26    105       290       290       232       153        -79        -34.05  2419413  2419413             False
116  ZZ                     XANGAI     1    483       739       740       197       264         67         34.01  1668832  1668832             False
117  RR                   SÃO LUIZ     4     85       127       127       106        70        -36        -33.96  2285898  2285898             False
118  AP             FERREIRA GOMES    12     63       248       248       186       123        -63        -33.87  2352447  2352447             False
119  RJ                MANGARATIBA    54    134       346       346       278       184        -94        -33.81  2438579  2438579             False
120  AC                MÂNCIO LIMA     4    283       298       298       210       139        -71        -33.81  2280791  2280791             False
121  MA     PORTO RICO DO MARANHÃO    30    177       203       203       154       102        -52        -33.77  2287708  2287708             False
122  MS                    CAARAPÓ    28     75       297       297       160       214         54         33.75  2009553  2009553             False
123  AC               PORTO WALTER     4    325       208       206       169       112        -57        -33.73  2264624  2264624             False
124  RR               RORAINÓPOLIS     8     28       253       253       175       116        -59        -33.71  2285544  2285544             False
125  AC                      FEIJÓ     7     65       271       271       199       132        -67        -33.67  2264270  2264270             False
126  AP                     CUTIAS    10    439       254       254       205       136        -69        -33.66  2342508  2342508             False
127  AC             SENA MADUREIRA     3    156       170       168       122        81        -41        -33.61  2046638  2046638             False
128  AC                   TARAUACÁ     5     63       378       378       268       178        -90        -33.58  2269953  2269953             False
129  AP                     CUTIAS    10    252       282       283       221       147        -74        -33.48  2340873  2340873             False
130  RJ                MANGARATIBA    54    118       341       341       224       149        -75        -33.48  2393022  2393022             False
131  AP                     CUTIAS    10    417       287       287       236       157        -79        -33.47  2351493  2351493             False
132  PR          RIO BRANCO DO SUL   156    221       338       338       275       183        -92        -33.45  2089409  2089409             False

In [21]:
print('Urnas com variação > 10% em que o nº de eleitores aptos também mudou (possível remanejamento de seção)')
urnas_10[urnas_10.aptos_t1 != urnas_10.aptos_t2].reset_index(drop=True)

Urnas com variação > 10% em que o nº de eleitores aptos também mudou (possível remanejamento de seção)

      uf             municipio  zona  secao  aptos_t1  aptos_t2  votos_t1  votos_t2  diferenca  variacao_pct  urna_t1  urna_t2  urna_substituida
0     ZZ            WELLINGTON     1   1088       696       697        40        73         33         82.50  1652005  1652005             False
1     AC          PORTO WALTER     4    429       234       233       188        97        -91        -48.40  2260491  2260491             False
2     SP               DRACENA   149    119        39        27        34        18        -16        -47.06  1789952  1789952             False
3     AC  MARECHAL THAUMATURGO     4    294       271       270       237       126       -111        -46.84  2256772  2256772             False
4     AC  MARECHAL THAUMATURGO     4    162       262       260       225       124       -101        -44.89  2273101  2273101             False
...   ..                   ...   ...    ...       ...       ...       ...       ...        ...           ...      ...      ...               ...
1138  BA                 MARAÚ    78    144       366       367       279       307         28         10.04  1809729  1809729             False
1139  RJ        RIO DE JANEIRO   123    139       450       452       289       318         29         10.03  2131058  2131058             False
1140  BA            ITAPETINGA   140     71       393       392       299       329         30         10.03  2077043  2077043             False
1141  PE             GARANHUNS    56    216       387       388       309       340         31         10.03  1773689  1773689             False
1142  AL                MACEIÓ    33    155       445       444       339       373         34         10.03  2038159  2038159             False

[1143 rows x 13 columns]

### 5.3 Urnas presentes em só um turno

In [22]:
q('''
    SELECT CASE WHEN votos_t1 IS NULL THEN 'só 2º turno' ELSE 'só 1º turno' END AS situacao,
           uf, municipio, zona, secao, coalesce(votos_t1, votos_t2) AS votos
    FROM var_urna
    WHERE votos_t1 IS NULL OR votos_t2 IS NULL
    ORDER BY situacao, uf, municipio, zona, secao
''')

      situacao  uf municipio  zona  secao  votos
0  só 1º turno  ZZ   TRÍPOLI     1    443      2

### 5.4 (Complementar) Dispersão de votos por urna dentro de cada cidade

Coeficiente de variação (desvio padrão / média) do comparecimento por urna em cada município e turno.

In [23]:
dispersao = q('''
    SELECT turno, uf, municipio, count(*) AS urnas,
           round(avg(comparecimento), 1) AS media_votos_urna,
           round(stddev_samp(comparecimento), 1) AS desvio,
           round(100.0 * stddev_samp(comparecimento) / avg(comparecimento), 2) AS cv_pct,
           min(comparecimento) AS min_votos, max(comparecimento) AS max_votos
    FROM (SELECT 1 AS turno, * FROM secoes_t1 UNION ALL BY NAME SELECT 2 AS turno, * FROM secoes_t2)
    GROUP BY ALL
    HAVING count(*) >= 5
    ORDER BY cv_pct DESC
''')
dispersao.pivot_table(index=['uf', 'municipio'], columns='turno', values='cv_pct') \
         .rename(columns={1: 'cv_pct_t1', 2: 'cv_pct_t2'}) \
         .assign(delta=lambda d: d.cv_pct_t2 - d.cv_pct_t1) \
         .sort_values('delta', key=abs, ascending=False).head(50)

turno                       cv_pct_t1  cv_pct_t2  delta
uf municipio
PR INÁCIO MARTINS               32.74      40.27   7.53
AP CUTIAS                       17.73      24.62   6.89
GO ANHANGÜERA                   26.64      33.27   6.63
AP ITAUBAL                      21.42      27.90   6.48
AL OLHO D'ÁGUA GRANDE            6.05      11.83   5.78
AC PORTO WALTER                 21.91      27.29   5.38
MS PARANHOS                     22.94      17.81  -5.13
SP SANTO EXPEDITO               15.63      20.18   4.55
ZZ SÃO FRANCISCO                34.72      30.38  -4.34
AM CAAPIRANGA                    9.67      13.97   4.30
PI SANTA CRUZ DOS MILAGRES      11.61      15.89   4.28
ZZ WELLINGTON                   41.13      36.86  -4.27
AC MARECHAL THAUMATURGO         15.63      19.78   4.15
RJ MANGARATIBA                  11.41      15.48   4.07
AC MÂNCIO LIMA                  15.94      19.92   3.98
ZZ BARCELONA                    32.21      28.28  -3.93
   CAMBERRA                     58.60      54.71  -3.89
AM PRESIDENTE FIGUEIREDO        19.85      23.24   3.39
PB LAGOA DE DENTRO              13.20      16.57   3.37
ZZ ROMA                         37.43      34.09  -3.34
PA SAPUCAIA                      8.27      11.55   3.28
   SÃO JOÃO DA PONTA            17.99      21.23   3.24
AL CHÃ PRETA                    12.66      15.90   3.24
ZZ CHICAGO                      38.01      34.81  -3.20
RS ENGENHO VELHO                26.52      23.33  -3.19
MG SANTO HIPÓLITO               18.90      22.09   3.19
MT GENERAL CARNEIRO             24.38      27.55   3.17
PB RIACHO DE SANTO ANTÔNIO       3.38       6.52   3.14
MA HUMBERTO DE CAMPOS           24.67      27.81   3.14
   SÃO FRANCISCO DO BREJÃO      20.49      23.62   3.13
MG SENADOR CORTES               17.03      20.13   3.10
AP OIAPOQUE                     16.08      19.12   3.04
ZZ BUENOS AIRES                 14.97      11.94  -3.03
   SANTA CRUZ DE LA SIERRA      23.11      26.13   3.02
RS EREBANGO                     17.26      14.26  -3.00
AC FEIJÓ                        18.45      21.43   2.98
   SENA MADUREIRA               13.54      16.51   2.97
MS CAARAPÓ                      19.45      16.48  -2.97
CE SENADOR SÁ                   15.95      18.91   2.96
ZZ SYDNEY                       25.46      22.50  -2.96
MG SANTANA DO RIACHO            31.03      33.99   2.96
SP CAIUÁ                        31.85      34.80   2.95
RR SÃO LUIZ                     15.91      18.83   2.92
ZZ BOSTON                       23.16      20.25  -2.91
PI CARIDADE DO PIAUÍ             8.51      11.42   2.91
RR IRACEMA                      18.05      20.94   2.89
PA BREVES                       15.94      18.81   2.87
ZZ EDIMBURGO                    40.53      37.69  -2.84
MG SÃO GERALDO DA PIEDADE       15.27      18.11   2.84
AM CAREIRO DA VÁRZEA            22.20      25.03   2.83

## 6. Testes de indícios de manipulação (eleição para Presidente)

Testes estatísticos usuais de *election forensics*. Eles detectam padrões típicos de fraude na contagem
(inclusão de votos, números inventados, urnas destoantes), mas **não provam ausência de fraude** nem detectam
compra de votos ou coação.

| Teste | O que indicaria problema |
|---|---|
| 6.1 Candidato único × local de votação | urna 100% para um candidato cercada de urnas com votação diferente |
| 6.2 Distribuição do % por urna | pico artificial em 0% ou 100% |
| 6.3 Comparecimento ≥ 97% | muitas urnas com comparecimento quase total e voto concentrado |
| 6.4 Comparecimento × % do candidato | correlação positiva forte / nuvem de urnas indo para (100%, 100%) |
| 6.5 Último dígito | frequência de cada dígito muito diferente de 10% |
| 6.6 Variação 1º→2º turno × voto | urnas com variação > 10% com mudança de voto diferente das demais |
| 6.7 Urnas substituídas | resultado diferente nas urnas trocadas entre os turnos |

In [24]:
_ = con.execute('''
    CREATE OR REPLACE TEMP TABLE pres AS
    SELECT turno, uf, cd_municipio, zona, secao, any_value(local_votacao) AS local_votacao,
           coalesce(sum(votos) FILTER (WHERE nr_votavel = 13), 0) AS lula,
           coalesce(sum(votos) FILTER (WHERE nr_votavel = 22), 0) AS flavio,
           sum(votos) FILTER (WHERE tipo_votavel = 'Nominal') AS validos,
           max(aptos) AS aptos, max(comparecimento) AS comparecimento, any_value(nr_urna) AS nr_urna
    FROM (SELECT 1 AS turno, * FROM votos_t1 UNION ALL BY NAME SELECT 2 AS turno, * FROM votos_t2)
    WHERE cargo = 'Presidente'
    GROUP BY ALL
''')

### 6.1 Urnas de candidato único × município e local de votação (2º turno, ≥ 30 votos válidos)

Se as demais urnas do mesmo local também votaram ~100% no mesmo candidato, o padrão é do local
(típico de aldeias indígenas e comunidades isoladas), não de uma urna isolada.

In [25]:
unico_local = q('''
    WITH mun AS (SELECT uf, cd_municipio, 100.0 * sum(lula) / sum(validos) AS pct_lula_municipio
                 FROM pres WHERE turno = 2 GROUP BY ALL),
         loc AS (SELECT uf, cd_municipio, zona, local_votacao, count(*) AS urnas_no_local,
                        100.0 * sum(lula) / sum(validos) AS pct_lula_local
                 FROM pres WHERE turno = 2 GROUP BY ALL)
    SELECT p.uf, s.municipio, p.zona, p.secao, p.local_votacao, p.validos,
           CASE WHEN p.lula = p.validos THEN 'LULA' ELSE 'FLAVIO BOLSONARO' END AS candidato,
           round(pct_lula_municipio, 1) AS pct_lula_municipio,
           round(pct_lula_local, 1) AS pct_lula_local, urnas_no_local
    FROM pres p
    JOIN (SELECT uf, cd_municipio, zona, secao, municipio FROM secoes_t2) s USING (uf, cd_municipio, zona, secao)
    JOIN mun USING (uf, cd_municipio)
    JOIN loc USING (uf, cd_municipio, zona, local_votacao)
    WHERE p.turno = 2 AND p.validos >= 30 AND (p.lula = p.validos OR p.flavio = p.validos)
    ORDER BY abs(pct_lula_local - pct_lula_municipio) DESC
''')
display(unico_local.groupby('candidato')[['pct_lula_municipio', 'pct_lula_local']].describe().T)
unico_local

candidato                 FLAVIO BOLSONARO   LULA
pct_lula_municipio count              4.00 103.00
                   mean              39.53  67.19
                   std               25.25  17.60
                   min               13.90  18.20
                   25%               21.70  55.70
                   50%               37.25  73.80
                   75%               55.08  80.00
                   max               69.70  90.90
pct_lula_local     count              4.00 103.00
                   mean               0.17  99.88
                   std                0.35   0.28
                   min                0.00  98.50
                   25%                0.00 100.00
                   50%                0.00 100.00
                   75%                0.17 100.00
                   max                0.70 100.00

     uf                  municipio  zona  secao  local_votacao  validos         candidato  pct_lula_municipio  pct_lula_local  urnas_no_local
0    MT          GUARANTÃ DO NORTE    44    284           1171   145.00              LULA               18.20          100.00               1
1    RR                    CAROEBE     4    141           1163    44.00              LULA               20.80          100.00               1
2    MT                   CONFRESA    28    200           1120   309.00              LULA               25.80           99.80               2
3    PA         SÃO FÉLIX DO XINGU    53    218           1350   273.00              LULA               27.60          100.00               1
4    PA         SÃO FÉLIX DO XINGU    53    217           1341   145.00              LULA               27.60          100.00               1
5    AC            CRUZEIRO DO SUL     4    457           2291   137.00              LULA               28.90           99.20               2
6    PA                     CHAVES    17     41           1252    48.00  FLAVIO BOLSONARO               69.70            0.00               1
7    MT      PORTO ALEGRE DO NORTE    28    191           1090    61.00              LULA               34.00          100.00               1
8    PA                   ALTAMIRA    18    519           3000    35.00              LULA               36.20          100.00               1
9    PA                   ALTAMIRA    18    516           3018    52.00              LULA               36.20          100.00               1
10   MT         PEIXOTO DE AZEVEDO    33    255           1139   179.00              LULA               37.60          100.00               1
11   RO                PORTO VELHO     6    516           1767   104.00              LULA               38.30          100.00               1
12   MT            BARRA DO GARÇAS     9    531           1511   119.00              LULA               38.90           99.10               2
13   PA                PARAUAPEBAS   106    330           1210   212.00              LULA               40.40           99.80               3
14   PA                PARAUAPEBAS   106    365           1210   197.00              LULA               40.40           99.80               3
15   PA                PARAGOMINAS    42    214           1503    54.00              LULA               41.30          100.00               1
16   MS               ARAL MOREIRA    19    313           1171    56.00              LULA               43.80          100.00               1
17   ES                    ARACRUZ    20    232           1627    41.00              LULA               44.30          100.00               1
18   PA                   ALENQUER    21    234           2216    60.00              LULA               48.90          100.00               1
19   PA               JACAREACANGA   102     44           1244    50.00  FLAVIO BOLSONARO               50.20            0.00               1
20   AM                     JAPURÁ    48     12           1074   224.00              LULA               52.50          100.00               1
21   PR                 ORTIGUEIRA   167     96           1562   314.00              LULA               52.90           99.50               2
22   RS                     VIAMÃO    59    591           2208    65.00              LULA               54.80          100.00               1
23   RS                     VIAMÃO    59    590           2194    39.00              LULA               54.80          100.00               1
24   PA                     AVEIRO    34    660           1481   106.00              LULA               55.00          100.00               1
25   PA                  ORIXIMINÁ    38    259           2070   133.00              LULA               55.20          100.00               1
26   PA                  ORIXIMINÁ    38    260           2097   152.00              LULA               55.20          100.00               1
27   PA                  ORIXIMINÁ    38    243           2046    35.00              LULA               55.20          100.00               1
28   AC                     JORDÃO     5     65           1074   126.00              LULA               56.20           99.70               3
29   AC                     JORDÃO     5    125           1074   123.00              LULA               56.20           99.70               3
30   AM                      JURUÁ    50     19           1180   149.00              LULA               59.90          100.00               1
31   MG                    SALINAS   244    256           1562    47.00              LULA               60.60          100.00               1
32   MA                     GRAJAÚ    15    405           2100   102.00              LULA               60.90          100.00               1
33   MA               MONTES ALTOS   103     80           1090   298.00              LULA               63.00           99.50               2
34   CE                    AQUIRAZ    66    334           2151    32.00              LULA               64.90          100.00               1
35   TO             TOCANTINÓPOLIS     9    184           1406    59.00              LULA               67.00          100.00               1
36   TO             TOCANTINÓPOLIS     9    192           1252   155.00              LULA               67.00           99.20               4
37   AM                  TABATINGA    36     96           1260   338.00              LULA               67.90          100.00               1
38   AM                  TABATINGA    36     61           1201   354.00              LULA               67.90          100.00               1
39   TO                   GOIATINS    32     61           1180   162.00              LULA               68.30          100.00               2
40   TO                   GOIATINS    32     60           1171   108.00              LULA               68.30          100.00               1
41   TO                   GOIATINS    32     84           1180   174.00              LULA               68.30          100.00               2
42   PA                   ALMEIRIM    55    128           1600   156.00              LULA               69.00          100.00               1
43   BA                   SENTO SÉ    96    119           1643    62.00              LULA               69.60          100.00               1
44   PA                       MOJU    37    120           1503    41.00              LULA               70.40          100.00               1
45   MA                      VIANA    20    258           1945   100.00              LULA               72.00          100.00               1
46   RR                   UIRAMUTÃ     7     63           1147   256.00              LULA               72.90          100.00               1
47   RR                   UIRAMUTÃ     7     62           1139   216.00              LULA               72.90          100.00               2
48   RR                   UIRAMUTÃ     7    104           1198   138.00              LULA               72.90          100.00               1
49   RR                   UIRAMUTÃ     7    124           1279    48.00              LULA               72.90          100.00               1
50   RR                   UIRAMUTÃ     7    108           1139   126.00              LULA               72.90          100.00               2
51   RR                   UIRAMUTÃ     7     61           1120   189.00              LULA               72.90           99.70               2
52   AM  SANTA ISABEL DO RIO NEGRO    30     26           1139   229.00              LULA               73.80          100.00               3
53   AM  SANTA ISABEL DO RIO NEGRO    30     22           1139   236.00              LULA               73.80          100.00               3
54   AM  SANTA ISABEL DO RIO NEGRO    30     30           1139    72.00              LULA               73.80          100.00               3
55   TO                     PARANÃ    18     87           1252    33.00              LULA               74.20          100.00               1
56   RR                   UIRAMUTÃ     7    113           1244   190.00              LULA               72.90           98.50               2
57   AM       SANTO ANTÔNIO DO IÇÁ    47      9           1040   329.00              LULA               74.10           99.50               4
58   AM                   CARAUARI    21     96           1414   113.00              LULA               74.70          100.00               1
59   TO                 TOCANTÍNIA     5     55           1031   196.00              LULA               74.00           99.10               3
60   AM       SANTO ANTÔNIO DO IÇÁ    47     87           1180   315.00              LULA               74.10           99.20               3
61   RS              CÂNDIDO GODÓI   166     81           1228    82.00  FLAVIO BOLSONARO               24.30            0.00               1
62   MA               SANTA HELENA    83    170           1538    54.00              LULA               75.80          100.00               1
63   MA               SANTA HELENA    83    179           1562    55.00              LULA               75.80          100.00               1
64   MA              MARANHÃOZINHO   101     78           1104   176.00              LULA               76.50           99.20               2
65   BA              ÉRICO CARDOSO   111    250           1228    44.00              LULA               77.50          100.00               1
66   AM                URUCURITUBA     3    252           1112   101.00              LULA               77.60          100.00               1
67   BA                       IAÇU   193    116           1210    40.00              LULA               77.80          100.00               1
68   AM           ATALAIA DO NORTE    42     29           1112   325.00              LULA               77.80          100.00               1
69   AM           ATALAIA DO NORTE    42     30           1155   142.00              LULA               77.80          100.00               1
70   AM           ATALAIA DO NORTE    42     28           1147   136.00              LULA               77.80          100.00               1
71   AM           ATALAIA DO NORTE    42     37           1171   122.00              LULA               77.80          100.00               1
72   AM           ATALAIA DO NORTE    42     26           1120   302.00              LULA               77.80          100.00               1
73   MA               BARREIRINHAS    56    254           2259    95.00              LULA               77.80          100.00               1
74   PA                      VISEU    14    236           2151    64.00              LULA               79.60          100.00               1
75   MA                  SÃO BENTO    38    167           1368    96.00              LULA               79.90          100.00               1
76   AM   SÃO GABRIEL DA CACHOEIRA    19     65           1546   224.00              LULA               80.00          100.00               2
77   AM   SÃO GABRIEL DA CACHOEIRA    19     92           1546   215.00              LULA               80.00          100.00               2
78   AM   SÃO GABRIEL DA CACHOEIRA    19     87           1600   222.00              LULA               80.00          100.00               1
79   AM   SÃO GABRIEL DA CACHOEIRA    19    120           1708   126.00              LULA               80.00          100.00               1
80   MA                    TURIAÇU    39    195           2224    73.00              LULA               80.30          100.00               1
81   MA                    TURIAÇU    39    206           2267    91.00              LULA               80.30          100.00               1
82   MA                    TURIAÇU    39    162           2089   157.00              LULA               80.30          100.00               1
83   MG                 LUISLÂNDIA    50    224           1139    69.00              LULA               80.30          100.00               1
84   MA                    TURIAÇU    39     58           1309   164.00              LULA               80.30           99.70               2
85   AM   SÃO GABRIEL DA CACHOEIRA    19      1           1090   167.00              LULA               80.00           99.30               3
86   MA                  ALCÂNTARA    52     85           1554    79.00              LULA               80.90          100.00               1
87   MA                  ALCÂNTARA    52     86           1562    44.00              LULA               80.90          100.00               1
88   CE                    PORANGA    40    208           1368    54.00              LULA               81.00          100.00               1
89   AM          BENJAMIN CONSTANT    20    117           1341   231.00              LULA               81.30          100.00               1
90   AM          BENJAMIN CONSTANT    20     89           1244   238.00              LULA               81.30           99.80               2
91   MA                   CURURUPU    14    195           1686    54.00              LULA               82.20          100.00               1
92   AM                  PARINTINS     4    280           2054    88.00              LULA               82.80          100.00               1
93   AM                  PARINTINS     4    130           1600   220.00              LULA               82.80          100.00               1
94   MA      ÁGUA DOCE DO MARANHÃO    12    145           1210   189.00              LULA               83.20          100.00               1
95   AM      SÃO PAULO DE OLIVENÇA    22    114           1228   244.00              LULA               83.40          100.00               1
96   AM                      MAUÉS     5    176           1406   333.00              LULA               83.60          100.00               2
97   AM                      MAUÉS     5    179           1406   123.00              LULA               83.60          100.00               2
98   AM      SÃO PAULO DE OLIVENÇA    22     71           1171   298.00              LULA               83.40           99.80               3
99   MA              PRIMEIRA CRUZ    32    193           1147    42.00              LULA               85.90          100.00               1
100  MA              PRIMEIRA CRUZ    32     90           1384    42.00              LULA               85.90          100.00               1
101  RS            ARROIO DO PADRE    34    433           1040   116.00  FLAVIO BOLSONARO               13.90            0.70               2
102  PE                   FLORESTA    72    119           1287   227.00              LULA               85.70           98.90               2
103  BA            BARRA DO MENDES   176    151           1422    69.00              LULA               87.70          100.00               1
104  MA        SERRANO DO MARANHÃO   107     89           1147    74.00              LULA               90.10          100.00               1
105  MA        SERRANO DO MARANHÃO   107     87           1120    83.00              LULA               90.10          100.00               1
106  AM                BARREIRINHA    26     62           1414   261.00              LULA               90.90           99.70               3

### 6.2 Distribuição das urnas por % de votos válidos em Lula (2º turno, ≥ 50 válidos)

In [26]:
q('''
    SELECT CAST(floor(100.0 * lula / validos / 5) * 5 AS INTEGER) AS faixa_pct_lula, count(*) AS urnas
    FROM pres WHERE turno = 2 AND validos >= 50
    GROUP BY 1 ORDER BY 1
''').set_index('faixa_pct_lula').T

faixa_pct_lula  0    5     10    15     20     25     30     35     40     45     50     55     60     65     70     75     80     85    90    95   100
urnas            39  329  1481  5301  13427  24363  37667  49751  57684  55905  50629  43229  38978  32235  27590  24056  18117  10946  5094  1619   88

### 6.3 Urnas com comparecimento ≥ 97% (≥ 50 aptos)

In [27]:
display(q('''
    SELECT turno,
           count(*) FILTER (WHERE comparecimento >= 0.97 * aptos) AS urnas_97pct,
           count(*) FILTER (WHERE comparecimento = aptos)         AS urnas_100pct,
           sum(comparecimento) FILTER (WHERE comparecimento >= 0.97 * aptos) AS votos_nessas_urnas,
           round(100.0 * sum(lula) FILTER (WHERE comparecimento >= 0.97 * aptos)
                 / sum(validos) FILTER (WHERE comparecimento >= 0.97 * aptos), 1) AS pct_lula_nessas_urnas,
           round(100.0 * sum(lula) / sum(validos), 1) AS pct_lula_geral
    FROM pres WHERE aptos >= 50 GROUP BY turno ORDER BY turno
'''))
alto_comparecimento = q('''
    SELECT p.turno, p.uf, s.municipio, p.zona, p.secao, p.aptos, p.comparecimento,
           round(100.0 * p.comparecimento / p.aptos, 1) AS pct_comparecimento,
           p.lula, p.flavio, p.validos, round(100.0 * p.lula / p.validos, 1) AS pct_lula
    FROM pres p JOIN (SELECT 1 AS turno, uf, cd_municipio, zona, secao, municipio FROM secoes_t1 UNION ALL
                      SELECT 2 AS turno, uf, cd_municipio, zona, secao, municipio FROM secoes_t2) s USING (turno, uf, cd_municipio, zona, secao)
    WHERE p.aptos >= 50 AND p.comparecimento >= 0.97 * p.aptos
    ORDER BY pct_comparecimento DESC, p.validos DESC
''')
alto_comparecimento

   turno  urnas_97pct  urnas_100pct  votos_nessas_urnas  pct_lula_nessas_urnas  pct_lula_geral
0      1          124            10           15,365.00                  71.50           45.20
1      2          142             9           19,843.00                  74.70           51.80

     turno  uf                  municipio  zona  secao  aptos  comparecimento  pct_comparecimento   lula  flavio  validos  pct_lula
0        2  RN                   CARAÚBAS    36     69    163             163              100.00 134.00   25.00   159.00     84.30
1        1  BA              SANTO ESTEVÃO   143    230    168             168              100.00 138.00    9.00   155.00     89.00
2        2  CE  DEPUTADO IRAPUAN PINHEIRO    55    160    127             127              100.00 104.00   21.00   125.00     83.20
3        1  CE  DEPUTADO IRAPUAN PINHEIRO    55    160    127             127              100.00  98.00   20.00   122.00     80.30
4        1  PA                 SALVATERRA     3    153    120             120              100.00  89.00   26.00   117.00     76.10
..     ...  ..                        ...   ...    ...    ...             ...                 ...    ...     ...      ...       ...
261      2  BA                PÉ DE SERRA   114    269    134             130               97.00  98.00   27.00   125.00     78.40
262      2  MG     SÃO SEBASTIÃO DO OESTE   139    105    101              98               97.00  47.00   46.00    93.00     50.50
263      1  RJ                    RESENDE    31    365     67              65               97.00  18.00   42.00    64.00     28.10
264      2  PE   SANTA CRUZ DO CAPIBARIBE   109    182     67              65               97.00  44.00   19.00    63.00     69.80
265      1  PE                   PAULISTA   146    353     67              65               97.00  31.00   24.00    63.00     49.20

[266 rows x 12 columns]

### 6.4 Comparecimento × % de Lula por urna (2º turno, ≥ 50 aptos, sem exterior)

Inclusão de votos em massa gera correlação positiva e uma “cauda” de urnas indo para o canto
(comparecimento 100%, voto 100%). A tabela é um histograma 2D: linhas = faixa de comparecimento, colunas = faixa de % Lula.

In [28]:
fp = q('''
    SELECT uf, 1.0 * comparecimento / aptos AS comparecimento, 1.0 * lula / validos AS pct_lula
    FROM pres WHERE turno = 2 AND aptos >= 50 AND validos > 0 AND uf <> 'ZZ'
''')
print(f"Correlação nacional comparecimento × % Lula: {fp.comparecimento.corr(fp.pct_lula):.3f}")
display(fp.groupby('uf').apply(lambda g: g.comparecimento.corr(g.pct_lula)).round(3).rename('correlacao').to_frame().T)

faixas_c = pd.cut(fp.comparecimento, bins=[i / 100 for i in range(50, 101, 5)], include_lowest=True)
faixas_v = pd.cut(fp.pct_lula, bins=[i / 10 for i in range(0, 11)], include_lowest=True)
pd.crosstab(faixas_c, faixas_v).rename_axis(index='comparecimento', columns='% Lula')

Correlação nacional comparecimento × % Lula: 0.049

uf            AC    AL    AM    AP   BA    CE   DF    ES    GO    MA    MG    MS   MT   PA    PB    PE    PI    PR    RJ    RN   RO   RR    RS    SC    SE    SP    TO
correlacao -0.21 -0.36 -0.35 -0.26 0.07 -0.26 0.01 -0.17 -0.23 -0.26 -0.22 -0.25 0.01 0.10 -0.30 -0.33 -0.07 -0.25 -0.17 -0.04 0.11 0.13 -0.47 -0.25 -0.26 -0.13 -0.11

% Lula          (-0.001, 0.1]  (0.1, 0.2]  (0.2, 0.3]  (0.3, 0.4]  (0.4, 0.5]  (0.5, 0.6]  (0.6, 0.7]  (0.7, 0.8]  (0.8, 0.9]  (0.9, 1.0]
comparecimento
(0.499, 0.55]               3           5           8          19          37          54          38          44          33          10
(0.55, 0.6]                 2          14          36          88         142         166         141         147          84          32
(0.6, 0.65]                 7          45         159         314         548         635         548         460         246         103
(0.65, 0.7]                 7         146         612        1606        2918        2759        1942        1355         806         296
(0.7, 0.75]                31         432        2573        7555       13332       10666        6530        4017        2455         689
(0.75, 0.8]                42        1177        8727       24874       34604       25192       15361       10121        6002        1438
(0.8, 0.85]                63        2325       15820       38610       46120       33226       23526       18854       10037        1899
(0.85, 0.9]               128        2090        8889       14085       15949       16736       18743       14450        7461        1560
(0.9, 0.95]                80         577         884         794        1058        2646        3671        2095        1483         619
(0.95, 1.0]                 9          26          22          27          61          69          85          84         116         109

### 6.5 Último dígito das contagens de votos (Lula e Flávio, contagens ≥ 10) — esperado ≈ 10% cada

In [29]:
q('''
    SELECT turno, votos % 10 AS digito, count(*) AS n
    FROM (SELECT turno, lula AS votos FROM pres UNION ALL SELECT turno, flavio FROM pres)
    WHERE votos >= 10
    GROUP BY ALL
''').pivot(index='turno', columns='digito', values='n').apply(lambda r: (100 * r / r.sum()).round(2), axis=1)

digito  0.00  1.00  2.00  3.00  4.00  5.00  6.00  7.00  8.00  9.00
turno
1      10.07  9.97  9.96 10.05 10.01 10.01 10.02  9.97  9.98  9.97
2      10.02  9.97  9.99 10.04  9.99 10.00 10.01 10.00  9.99  9.98

### 6.6 Variação de comparecimento 1º→2º turno × mudança de voto

`lula_vs_flavio_1t` = % de Lula no confronto direto com Flávio no 1º turno, comparável ao 2º turno.

In [30]:
q(f'''
    WITH a AS (SELECT * FROM pres WHERE turno = 1), b AS (SELECT * FROM pres WHERE turno = 2)
    SELECT CASE WHEN abs(b.comparecimento - a.comparecimento) > {LIMIAR_VARIACAO} * a.comparecimento
                THEN 'variação > 10%' ELSE 'demais urnas' END AS grupo,
           count(*) AS urnas,
           round(100.0 * sum(a.lula) / sum(a.lula + a.flavio), 2) AS lula_vs_flavio_1t,
           round(100.0 * sum(b.lula) / sum(b.validos), 2) AS lula_2t,
           round(100.0 * sum(b.lula) / sum(b.validos) - 100.0 * sum(a.lula) / sum(a.lula + a.flavio), 2) AS ganho_lula_pp
    FROM a JOIN b USING (uf, cd_municipio, zona, secao)
    WHERE a.comparecimento > 0
    GROUP BY 1
''')

            grupo   urnas  lula_vs_flavio_1t  lula_2t  ganho_lula_pp
0    demais urnas  486625              48.77    51.57           2.80
1  variação > 10%   12580              58.11    60.94           2.83

In [31]:
print('Cidades com queda/alta de comparecimento > 15%: variação de voto acompanha o resto do país?')
q('''
    WITH a AS (SELECT uf, cd_municipio, sum(comparecimento) c1, sum(lula) l1, sum(flavio) f1
               FROM pres WHERE turno = 1 GROUP BY ALL),
         b AS (SELECT uf, cd_municipio, sum(comparecimento) c2, sum(lula) l2, sum(validos) v2
               FROM pres WHERE turno = 2 GROUP BY ALL)
    SELECT uf, m.municipio, c1 AS votos_t1, c2 AS votos_t2,
           round(100.0 * (c2 - c1) / c1, 1) AS variacao_pct,
           round(100.0 * l1 / (l1 + f1), 1) AS lula_vs_flavio_1t,
           round(100.0 * l2 / v2, 1) AS lula_2t,
           round(100.0 * l2 / v2 - 100.0 * l1 / (l1 + f1), 1) AS ganho_lula_pp
    FROM a JOIN b USING (uf, cd_municipio)
    JOIN (SELECT DISTINCT uf, cd_municipio, municipio FROM secoes_t1) m USING (uf, cd_municipio)
    WHERE abs(c2 - c1) > 0.15 * c1
    ORDER BY variacao_pct
''')

Cidades com queda/alta de comparecimento > 15%: variação de voto acompanha o resto do país?

    uf             municipio  votos_t1  votos_t2  variacao_pct  lula_vs_flavio_1t  lula_2t  ganho_lula_pp
0   AP               ITAUBAL  7,354.00  5,239.00        -28.80              54.00    57.00           3.00
1   AP                CUTIAS  5,191.00  3,758.00        -27.60              55.50    60.10           4.70
2   AC          PORTO WALTER  6,520.00  4,792.00        -26.50              53.60    53.30          -0.30
3   AC  MARECHAL THAUMATURGO  9,352.00  7,051.00        -24.60              38.50    40.20           1.70
4   AP              PRACUÚBA  3,313.00  2,510.00        -24.20              52.30    59.70           7.40
5   AP        FERREIRA GOMES  6,260.00  4,764.00        -23.90              49.10    52.10           3.00
6   AP                 AMAPÁ  6,262.00  4,971.00        -20.60              59.70    63.40           3.60
7   AP       TARTARUGALZINHO  9,274.00  7,484.00        -19.30              55.30    58.40           3.10
8   RR               AMAJARI  6,520.00  5,302.00        -18.70              23.50    27.50           4.00
9   AP               MAZAGÃO 18,989.00 15,596.00        -17.90              63.40    64.80           1.40
10  AP        SERRA DO NAVIO  3,040.00  2,499.00        -17.80              38.40    40.20           1.80
11  RR              SÃO LUIZ  5,114.00  4,207.00        -17.70              26.10    29.30           3.20
12  AP              CALÇOENE  7,009.00  5,773.00        -17.60              55.10    58.00           2.90
13  RR               IRACEMA  6,153.00  5,106.00        -17.00              22.80    25.90           3.10
14  RR             CARACARAÍ 12,452.00 10,420.00        -16.30              25.80    28.10           2.30
15  AC              TARAUACÁ 22,603.00 19,112.00        -15.40              39.40    42.90           3.40
16  AC        SENA MADUREIRA 24,661.00 20,888.00        -15.30              25.80    27.70           1.90
17  MA         PRIMEIRA CRUZ  9,220.00  7,817.00        -15.20              83.50    85.90           2.40
18  RR    SÃO JOÃO DA BALIZA  4,843.00  4,112.00        -15.10              25.80    29.60           3.80
19  ZZ                  FARO  2,761.00  3,176.00         15.00              45.70    47.30           1.70
20  ZZ                LISBOA 28,643.00 33,002.00         15.20              58.60    60.10           1.50
21  ZZ               BANGKOK    102.00    118.00         15.70              44.00    48.30           4.30
22  ZZ                NASSAU     19.00     22.00         15.80              37.50    30.00          -7.50
23  ZZ       CIUDAD DEL ESTE  2,586.00  3,001.00         16.00               8.30     8.50           0.20
24  ZZ               MUNIQUE  5,423.00  6,316.00         16.50              72.30    73.20           0.90
25  ZZ                BOSTON 16,390.00 19,304.00         17.80              25.90    28.40           2.50
26  ZZ               ZURIQUE  6,001.00  7,086.00         18.10              55.70    58.80           3.10
27  ZZ         SÃO FRANCISCO  3,896.00  4,610.00         18.30              62.20    65.20           3.00
28  ZZ               CHICAGO  2,779.00  3,295.00         18.60              60.90    63.80           2.90
29  ZZ           LOS ANGELES  4,609.00  5,473.00         18.70              51.70    55.00           3.40
30  ZZ              MARSELHA    875.00  1,049.00         19.90              87.30    89.20           1.90
31  ZZ                SYDNEY  5,694.00  6,830.00         20.00              63.50    62.80          -0.70
32  ZZ                CANTÃO     99.00    119.00         20.20              57.80    59.30           1.50
33  ZZ                ABIDJÃ     44.00     53.00         20.50              64.90    58.50          -6.40
34  ZZ                  OSLO    909.00  1,097.00         20.70              74.90    76.80           1.80
35  ZZ             NOVA YORK 10,134.00 12,241.00         20.80              49.40    52.40           3.00
36  ZZ             EDIMBURGO    694.00    845.00         21.80              77.80    78.90           1.10
37  ZZ              HARTFORD  1,951.00  2,378.00         21.90              31.60    34.50           3.00
38  ZZ               JACARTA     31.00     38.00         22.60              29.60    39.50           9.80
39  ZZ             BARCELONA  5,185.00  6,381.00         23.10              78.80    77.30          -1.50
40  ZZ              TEL AVIV    730.00    902.00         23.60              15.00    19.20           4.20
41  ZZ              VARSÓVIA    291.00    363.00         24.70              73.80    75.10           1.30
42  ZZ         PORT OF SPAIN     19.00     24.00         26.30              28.60    42.90          14.30
43  ZZ                XANGAI    197.00    264.00         34.00              73.90    73.40          -0.50
44  ZZ       PASO LOS LIBRES      5.00      7.00         40.00              40.00    57.10          17.10
45  ZZ            WELLINGTON    339.00    526.00         55.20              78.50    80.50           2.00
46  ZZ        PORTO PRÍNCIPE      5.00      8.00         60.00             100.00    75.00         -25.00

### 6.7 Urnas substituídas entre os turnos (número de série diferente)

In [32]:
q('''
    WITH a AS (SELECT * FROM pres WHERE turno = 1), b AS (SELECT * FROM pres WHERE turno = 2)
    SELECT a.nr_urna <> b.nr_urna AS urna_substituida, count(*) AS urnas,
           round(100.0 * sum(a.lula) / sum(a.lula + a.flavio), 2) AS lula_vs_flavio_1t,
           round(100.0 * sum(b.lula) / sum(b.validos), 2) AS lula_2t
    FROM a JOIN b USING (uf, cd_municipio, zona, secao)
    GROUP BY 1
''')

   urna_substituida   urnas  lula_vs_flavio_1t  lula_2t
0             False  494770              48.99    51.78
1              True    4435              49.22    52.01

### Conclusão dos testes

Com os dados de 2026, nenhum teste apontou padrão de manipulação em larga escala:
- as urnas de candidato único ficam em locais de votação inteiros com voto homogêneo, não em urnas isoladas;
- a distribuição por urna é suave, sem pico artificial;
- comparecimento e % do candidato não têm correlação positiva (na maioria das UFs ela é negativa);
- o último dígito é uniforme;
- urnas com grande variação de comparecimento e urnas substituídas votaram como as demais.

Casos individuais, como as urnas com queda de comparecimento acima de 75%, só podem ser esclarecidos pelo TRE
(por exemplo, pela ata da seção).

## 7. Exportação

In [33]:
for nome, df in {'candidato_unico': unico, 'variacao_cidades': var_cidade,
                 'cidades_variacao_acima_10pct': cidades_10,
                 'urnas_variacao_acima_10pct': urnas_10,
                 'candidato_unico_vs_local': unico_local,
                 'urnas_comparecimento_97pct': alto_comparecimento}.items():
    df.to_csv(SAIDA / f'{nome}.csv', index=False, sep=';', encoding='utf-8-sig')
    print(f'{SAIDA / nome}.csv  ({len(df):,} linhas)')

/Users/alexjunq/Downloads/urnas/resultados/candidato_unico.csv  (204 linhas)
/Users/alexjunq/Downloads/urnas/resultados/variacao_cidades.csv  (5,716 linhas)
/Users/alexjunq/Downloads/urnas/resultados/cidades_variacao_acima_10pct.csv  (114 linhas)
/Users/alexjunq/Downloads/urnas/resultados/urnas_variacao_acima_10pct.csv  (12,580 linhas)
/Users/alexjunq/Downloads/urnas/resultados/candidato_unico_vs_local.csv  (107 linhas)
/Users/alexjunq/Downloads/urnas/resultados/urnas_comparecimento_97pct.csv  (266 linhas)